### PR TITLE
USWDS 3.9.0

### PR DESCRIPTION
**Pull request by thisisdano**
# What's new in USWDS 3.9.0
## Features

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-character-count` | - | - | - | **Enhanced the visual cue when `maxlength` is exceeded in the character count component.** Now, the component uses standard USWDS error styles to visually enhance the error state. (#5908)
`usa-date-picker`, `usa-date-range-picker` | Yes | - | - | **Added `aria-disabled` to the list of expected attributes in the date picker and date range picker components.** Now, the component will disable toggle when the `aria-disabled` attribute is present. (#6013)
`uswds-core`, `usa-layout-grid` | - | - | - | **Added new `$theme-utility-breakpoints-custom`  setting**.  This setting generates responsive variants of USWDS utilities at custom breakpoints. Values must be set with `px` values inside a Sass map. Thanks @jamigibbs! (#6048)

## Bug fixes

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-alert`, `usa-site-alert` | - | Yes | - | **Fixed a bug that caused `$theme-site-margins-width` to unexpectedly adjust the alignment inside the alert and site alert components.** Alignment on the alert and site alert components will likely shift from this change. Confirm that your implementation of the component aligns as expected. (#5636)<br><br>:warning: Considered breaking because the alignment and display of the alert may shift. 
`usa-button` | - | Yes | - | **Updated the width of unstyled buttons at narrow screen widths.**  Now, unstyled buttons receive a width of `auto` to better match USWDS link styles. Users should confirm that the variant visually displays as expected in their projects. Thanks @aduth! (#5631)<br><br>:warning: Considered breaking because the display of unstyled buttons will change at narrow screen widths. 
`usa-card` | - | Yes | - | **Fixed a bug that caused the component to ignore the `$theme-card-font-family` setting.** Confirm that your implementation of the card component displays with the expected font family.  (#5974)<br><br>:warning: Considered breaking because fonts in cards may change if you've set `$theme-card-font-family`. 
`usa-combo-box` | Yes | - | - | **Removed custom screen reader instructions in the combo box component.** Combo box now relies on the default instructions provided by screen readers. (#6022)
`usa-date-picker`, `usa-date-range-picker` | Yes | - | - | **Fixed a bug that caused `mouseover` events to prevent keyboard navigation.** Now when you hover your mouse over the date picker buttons, only the hover state will be triggered. (#5774)
`usa-header` | Yes | Yes | - | **Removed the CSS order property from the mobile view in standard variants of the header component.**  Now, the visual order of the component matches the tab order. If you would like to visually keep the search bar at the top of the menu, you will need to reorder your markup in the mobile view. (#6037)<br><br>:warning: Considered breaking because the position of the search bar will change in the mobile menu. 
`usa-footer`, `templates` | Yes | - | Yes | **Added the `autocomplete="email"` attribute to the big footer variant and the "Create an account" template.** This attribute allows the components to meet the standards outlined in [WCAG 1.3.5](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html). (#6002)<br><br>:pencil2: Teams should update their markup if they use an email field in their big footer. 
`usa-identifier` | - | - | Yes | **Updated the USA.gov link in Spanish versions of the identifier.** The link text now reads "Visite USAGov en Español" and the link url is now "https://www.usa.gov/es/". (#5892)<br><br>:pencil2: Teams should update this text if they use the Spanish-language identifier. 
`usa-memorable-date` | Yes | - | Yes | **Removed numeric representation of months in the memorable date component.** Recent usability testing indicated that having both numbers and names to represent months was confusing for screen reader users. (#6028)<br><br>:pencil2: Teams should update their memorable date component to remove the leading numbers. 
`usa-pagination` | Yes | - | - | **Added text underline styles to pagination links.** Pagination links are now visually consistent with other USWDS text links. (#5970)

## Dependencies and security

| Dependency name | Previous version | Updated version |
| --- | --- | --- |
| @18f/identity-stylelint-config | 4.0.0 | 4.1.0 |
| @babel/core | 7.24.5 | 7.25.2 |
| @babel/preset-env | 7.24.5 |  7.25.4 |
| @types/node | 20.12.11 | 20.14.10 |
| autoprefixer | 10.4.19 | 10.4.20 |
| axe-core | 4.9.1 | 4.10.0 |
| babel-loader | 9.1.3 | -- | 
| eslint-plugin-import | 2.29.1 | 2.30.0 | 
| eslint-plugin-no-unsanitized | 4.0.2 | 4.1.0 |
| gulp-changed | 4.0.3 | -- |
| gulp-clean | 0.4.0 | -- |
| gulp-cli | 2.3.0 | -- |
| mocha | 10.4.0 | 10.7.3 |
| normalize.css | 8.0.1 | -- |
| path | 0.12.7 | -- |
| postcss | 8.4.38 | 8.4.45 |
| postcss-preset-env | 9.5.11 | 9.6.0 |
| prettier | 3.2.5 | 3.3.3 |
| sass | 1.77.0 | 1.78.0 |
| sass-embedded | 1.77.0 | 1.78.0 |
| snyk | 1.1291.0 | 1.1293.0 |
| stylelint | 16.5.0 | 16.9.0 |
| typescript | 5.4.5 | 5.6.2 |
| webpack | 5.91.0 | 5.94.0 |

Thanks @aduth for contributing to our dependency updates and @skyf0l for fixing a typo in our package.json!

`0` vulnerabilities in regular dependencies (dependencies for USWDS projects installed with `npm install @uswds/uswds`)
`29` moderate, `26` high vulnerabilities in devDependencies (development dependencies).

Release TGZ SHA-256 hash: `140cb2162e6c60a6a6ecbc71d8d047819d4ec26f9dd6c7056bd4bd8a266af2ab`

### CODE REVIEW

**Review by amyleadem — APPROVED** [review]
LGTM!
Review the contents of the release: 

- [x] Confirm all USWDS items tagged as part of the release have been merged into develop
- [x] Confirm that release branch is up-to-date with develop
- [x] Confirm the hash in the release notes matches the .txt file and the .tgz file
- [x] To check the .tgz file, run: sha256sum ./wherever-the-release-is/uswds-uswds-[release number].tgz
- [x] Confirm the contents in the .tgz are present

Review the release description:
- [x] Confirm that user-facing changes from the release milestone are included in the release notes
- [x] Confirm the listed vulnerabilities are accurate
- [x] Confirm the listed dependency changes are accurate
- [x] Confirm “accessibility” items have been correctly identified
- [x] Confirm “breaking” items have been correctly identified
- [x] Confirm “markup change” items have been correctly identified
- [x] Confirm no spelling or grammatical errors
- [x] Confirm community contributors have been tagged where appropriate (Ex: “Thanks @octocat!”)

Also installed the `release-3.9.0` branch on uswds-site and it all looks good. Confirmed none of the breaking or markup changes had a negative effect on our site 👍

**Review by mejiaj — APPROVED** [review]
Changes look good. 

Unable to confirm the hash change on my end — I get `7a1a165e8cd06b7ae5dc2004d933d960dd348e9f66da4f99fa2457d5bfed7e5b` when I run `sha256sum ./uswds-uswds-3.9.0.tgz`. Not a blocker if it's accurate for both of you.

**Comment by thisisdano** [comment]
Getting the correct hash with my `sha256sum` of the release package: 140cb2162e6c60a6a6ecbc71d8d047819d4ec26f9dd6c7056bd4bd8a266af2ab

**Comment by amyleadem** [comment]
Same:
```
sha256sum ./downloads/uswds-uswds-3.9.0-1.tgz
140cb2162e6c60a6a6ecbc71d8d047819d4ec26f9dd6c7056bd4bd8a266af2ab  ./downloads/uswds-uswds-3.9.0-1.tgz
```

**Pull request merged**
