### PR TITLE
Change direction of dropdown arrow when opened 

### LINKED ISSUE #2616: [Header]: Change direction of dropdown arrow when opened
via @mariamarrero in #1905

>Have you considered changing the direction of the arrow on the menu to pointing 'up' or replacing it with an 'X' once the menu is opened? It would stand out against other arrows pointing down and will give a visual cue that you need to click on the menu to close it.
>
>PS: We have gotten direct comments from users on these 2 issues.

dropdown up or down

### PR DESCRIPTION
**Pull request by greensteph**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/sg-header-arrow/components/preview/header--default.html)

Closes #2616 

Added up arrow images assets.
Swapped out down arrow for up arrow when the menu is expanded.

### CODE REVIEW

**Comment by thisisdano** [comment]
Hm — I'm not seeing this in action here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-grid-important/components/preview/header--default.html

Am I missing something?

**Comment by saracope** [comment]
@thisisdano It looks like you may be on the wrong branch? You linked to dw-grid-important. But the change is on https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/sg-header-arrow/components/preview/header--default.html

**Comment by thisisdano** [comment]
Oooof. Poor tab management skills.

**Comment by thisisdano** [comment]
Nice work — sorry for the confusion.

**Pull request merged**
