### PR TITLE
Fix internal page link errors from mobile navigation

### LINKED ISSUE #3058: Mobile navigation breaks when using same-page anchor links
If a `usa-nav__link` in the header navigation points to an in-page anchor link (like `#internal-link`), then the javascript throws an error:

```
Uncaught Error: No toggle target found with id: "null"
```

This seems to be because our javascript expects `usa-nav__link` to either link out to a new page or be a trigger that opens or shuts a submenu dropdown/accordion.

**new page:**
```
<li class="usa-nav__primary-item">
    <a class="usa-nav__link" href="https://link.to.comain.tld/page">
      <span>Simple link</span></a>
</li>
```

**trigger:**
```
<li class="usa-nav__primary-item">
  <button class="usa-accordion__button usa-nav__link" aria-expanded="false" aria-controls="extended-nav-section-two">
    <span>Section</span></button>
  <ul id="extended-nav-section-two" class="usa-nav__submenu" hidden="">
    <li class="usa-nav__submenu-item">
      <a href="#">Navigation link</a>
    </li>
    <li class="usa-nav__submenu-item">
      <a href="#">Navigation link</a>
    </li>
    <li class="usa-nav__submenu-item">
      <a href="#">Navigation link</a>
    </li>
  </ul>
</li>
```

**this one throws the error:**
```
<li class="usa-nav__primary-item">
  <a class="usa-nav__link" href="#test-section-id">
    <span>Simple link</span></a>
</li>
```

### Proposed solution
If  the `NAV_CONTROL` const in `navigation.js` is more strictly scoped to only apply to the trigger case — that is, when the the `usa-nav__link` is a button — then it would skip any link instance. 

```
const NAV_CONTROL = `button.${PREFIX}-nav__link`;
or
const NAV_CONTROL = `${PREFIX}-accordion__button.${PREFIX}-nav__link`;
```

### PR DESCRIPTION
**Pull request by thisisdano**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/fix-anchor-targets/components/preview/in-page-nav.html)  ✨

This PR constrains the scope of the `NAV_CONTROL` const in `navigation.js` to buttons only — specifically `button.${PREFIX}-nav__link`. This means that any toggle actions will only apply to actual toggle triggers and not to any links, internal or external.

- - -

Fixes #3058

### CODE REVIEW

**Comment by RobAWilkinson** [comment]
@thisisdano I've been bumping up against that bug as well, anything you're missing in this PR that you might need help with?

**Comment by thisisdano** [comment]
@RobAWilkinson Does this fix address the bug successfully? It works for me, but I'd been awaiting confirmation from a colleague.

**Comment by thisisdano** [comment]
Happy to merge and release it asap

**Comment by thisisdano** [comment]
Confirmed that this is working. Will merge.

**Pull request merged**
