### PR TITLE
Add a new var to control if layout grid gets !important

### PR DESCRIPTION
**Pull request by thisisdano**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-grid-important/)

Adds a `$theme-layout-grid-uses-important` bool to settings-general. Previously, layout grid would get `!important` if `$utilities-use-important` was set to true.

Fixes https://github.com/uswds/uswds/issues/2887

### CODE REVIEW

**Comment by maya** [comment]
Any reason to have `use` for utilities and `uses` for grid or should they be the same?

**Comment by thisisdano** [comment]
I guess I was going for grammatical correctness over consistency — do you think it makes better sense with `use`?

**Comment by maya** [comment]
Yes, I'd go with `use `.

**Comment by thisisdano** [comment]
OK, renamed

**Pull request merged**
