### PR TITLE
USWDS-3491: Fix accent-cool contrast issues with a more dependable contrast tool

### PR DESCRIPTION
**Pull request by mejiaj**
##  Description

Fixes https://github.com/uswds/uswds/issues/3491

Darkened `accent-cool-dark` and `accent-cool-darker` so that
`.usa-button--accent-cool`'s hover state meets WCAG AAA contrast standards.

This makes it consistent with its sibling buttons.

## Additional information

Include any of the following (as necessary): 
image

[Preview 👁](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-button-accent-cool-a11y/components/detail/buttons--accent-cool.html)

---

Is it possible to check for contrast issues with [axe-tester](https://github.com/uswds/uswds/blob/jm-button-accent-cool-a11y/spec/axe-tester.js#L14)?

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by thisisdano** [comment]
I think we need a smarter way for the button code to calculate whether it needs white or black text — I'm hesitant to just change the colors and call it a day...

**Comment by mejiaj** [comment]
Something like this?

https://css-tricks.com/programming-sass-to-create-accessible-color-combinations/

**Comment by thisisdano** [comment]
Added a couple new mixins, plus some other goodies.

**set-text-from-bg**(`$bg-token`, `$dark-token`, `$light-token`): for a given background color, use either the dark or light token for the text color, whichever assures proper contrast. prefer the light text color, and use `back` and `white` as the dark and light defaults. Sets _only_ the text color.

**set-text-and-bg**(`$bg-token`, `$dark-token`, `$light-token`): for a given background color, use either the dark or light token for the text color, whichever assures proper contrast. prefer the light text color, and use `back` and `white` as the dark and light defaults. Sets _both_ the background color and text color.

PLUS, **we can now do token grade checking in Sass**. Mostly. The relative luminance function I found is very very close to the output I get in our luminance tool, but not exactly the same. I don't knwo why not. So the checker has about 4 false positives. But if you turn the setting `$theme-check-colors` to `true` you can see it run. It's pretty slow and resource intensive, so you wouldn't want to do a luminance check to often. (It's why I built another function — **decompose**() — to convert a color token into a list of form `family`, `grade`, `variant`... it's a LOT faster.)

**Comment by mejiaj** [comment]
Just to confirm the above:
```sass
@include set-text-from-bg("primary-darker", "ink", "primary")
```
With this would I expect to get an error? 

---

```sass
 @include set-text-and-bg("primary-darker", "ink", "red-40")
```

The difference between `red-40` and `primary-darker` is 40. And `primary-darker` to `ink` is 10, shouldn't it set the greatest difference? In this case red-40. Or throw an error that neither are acceptable?

---

Variable name for doc's needs updating:

>But if you turn the setting $theme-check-colors to true you can see it run. 

`$theme-check-colors → $theme-test-colors`

Do you get these in your results when set to `true`?
```zsh
WARNING: green-warm-70v (#4b4e10) lum: 0.071 is not in the range 0.05, 0.07
    src/stylesheets/core/_functions.scss 1118:9   test-colors()
    src/stylesheets/core/_variables.scss 610:16   @import
    src/stylesheets/packages/_required.scss 14:9  @import
    src/stylesheets/uswds.scss 5:9                root stylesheet

WARNING: green-10v (#c5ee93) lum: 0.745 is not in the range 0.75, 0.82
    src/stylesheets/core/_functions.scss 1118:9   test-colors()
    src/stylesheets/core/_variables.scss 610:16   @import
    src/stylesheets/packages/_required.scss 14:9  @import
    src/stylesheets/uswds.scss 5:9                root stylesheet

WARNING: gray-cool-10 (#dfe1e2) lum: 0.744 is not in the range 0.75, 0.82
    src/stylesheets/core/_functions.scss 1118:9   test-colors()
    src/stylesheets/core/_variables.scss 610:16   @import
    src/stylesheets/packages/_required.scss 14:9  @import
    src/stylesheets/uswds.scss 5:9                root stylesheet
```

How would we expect users to use `decompose()` to run their own tests?

**Comment by thisisdano** [comment]
> `@include set-text-from-bg("primary-darker", "ink", "primary")`
This is most likely an error, if the difference between the background and neither light nor dark is 50 or more

>  @include set-text-and-bg("primary-darker", "ink", "red-40")
This should throw an error unless the difference is 50 or more. I don't want it just to use the biggest magic number, just the magic number that works.

Now we could rewrite it in the form (background, first choice, second choice), so there's more control over which color "wins" if both are sufficient. Or we could use the combination with the greatest magic number. And we could potentially pass in an optional third prop, like `level` which would default to `AA`, but could be `AALarge` or `AAA`...

As for decompose() — I'd probably consider it mostly an internal function.

And yes, I get some false positives, as the lum result from Sass is a little different from the lum I get in other checkers.

**Pull request merged**
