### PR TITLE
Time Picker: Preserve initial input value in Time Picker component

### LINKED ISSUE #4331: Default value on time picker component is ignored
### Describe the bug
When initializing a time picker with a default value, the default value is ignore.

Here's a sample of the issue: https://jsbin.com/qojusuj/edit?html,output

### Steps to reproduce the bug
1. Use time picker HTML
2. Update the value attribute to '12:00pm'
3. Verify the time picker is empty after initialization

### Expected behavior
I expect the matching value to be pre-selected if found in the combo box of times.

### System setup
- **USWDS version: 2.12.1**
- **Device: Tested on desktop, but pretty sure it's on all devices**
- **Operating system: Tested on Windows, but pretty sure it's on all devices**
- **Browser and version: Edge 93.0.961.52**

### Additional context
This is not an urgent issue for us.

### PR DESCRIPTION
**Pull request by aduth**
Partially addresses #4331

## Description

This pull request resolves an issue where if an enhanced Time Picker input has a value, the value is discarded during initialization, thereby preventing a developer from including an initial value for a time picker element.

## Additional information

Note that the Fractal component variant was based on a [similar Date Picker default value variant](https://github.com/uswds/uswds/blob/d9d4b91233aa8e650a32107fd58cde47278589ac/src/components/date-picker/date-picker.config.yml#L15-L19), but in that case the default value is expected to be assigned using a [`data-default-value` attribute](https://github.com/uswds/uswds/blob/d9d4b91233aa8e650a32107fd58cde47278589ac/src/components/date-picker/date-picker.njk#L6). ~Here, I chose instead to let the native `value` attribute be used since it is likely to be more intuitively understood as a way to control the input value, though I am open to revising this to `data-default-value` for consistency's sake.~ **Edit:** Per feedback, changed to `data-default-value` in [731748f](https://github.com/uswds/uswds/pull/4488/commits/731748f2c5ae05338fddbb46b1e04893f7c20f3c).

---

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by mejiaj — COMMENTED** [review]
This looks good! I'm leaning towards using `data-default-value` for consistency. What do you think @thisisdano?

**Comment by thisisdano** [comment]
I'm sorry, this one got past me. I agree with James, let's use `data-default-value` here. We will need a docs update to the Time Picker component to complete this task.

**Comment by aduth** [comment]
Updated to use `data-default-value` in [731748f](https://github.com/uswds/uswds/pull/4488/commits/731748f2c5ae05338fddbb46b1e04893f7c20f3c).

> We will need a docs update to the Time Picker component to complete this task.

Is there anything you need from me to help push this along? In the meantime, I'll remove the "Fixes" auto-close text from the original comment.

**Comment by mejiaj** [comment]
Hey @aduth, thanks for the reminder! Nothing wrong with the functionality, it works well. Just two outstanding issues.

The guidance on [Time picker](https://designsystem.digital.gov/components/time-picker/#using-the-time-picker-component) under the `Initialization properties` the defaults are set on the `usa-time-picker` element, not the input inside. 

Based on that we have these outstanding tasks:

- [ ] Decide if `data-default-value` be set on usa-time-picker **or** the input inside (like it currently is in PR)
- [ ]  Add new settings to docs in `time-picker.md`


https://github.com/uswds/uswds-site/blob/a4fa3a8bad7706c5e6ac6cf5cf4342d37c36f46d/_components/time-picker/time-picker.md?plain=1#L13-L23

**Comment by thisisdano** [comment]
@aduth Sorry for the backtracking, but after reviewing this issue again, we'd like to revert to your initial implementation, using the `value` attribute on the input. In this instance, respecting native properties and enabling progressive enhancement are more important than consistency between components. 

@mejiaj Let's also work to update components like Date Picker to work more like this.

**Comment by aduth** [comment]
Sounds good, pushed the revert in [fc6df77](https://github.com/uswds/uswds/pull/4488/commits/fc6df7742b3c08f463d9876828b493cf2475e6aa).

Still need to circle back on the documentation to wrap this up.

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
