### PR TITLE
[usa-header]: Prevent error if on a non-dropdown menu item

### PR DESCRIPTION
**Pull request by jkjustjoshing**
## Description

Prevents throwing an error when hitting ESC on a non-dropdown global nav item when an adjacent global nav item is open
resolves: #4798

## Additional information

Given the below DOM structure (mirror of what exists on [this demo site](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=components-header--default&args=&viewMode=story))
```
<ul class="usa-nav__primary usa-accordion">
    <li class="usa-nav__primary-item">
        <button type="button" class="usa-accordion__button usa-nav__link" aria-expanded="false" aria-controls="basic-nav-section-two"><span>DROPDOWN</span></button>
        <ul id="basic-nav-section-two" class="usa-nav__submenu" hidden="">
            <li class="usa-nav__submenu-item"><a href=""><span>&lt;Navigation link&gt;</span></a></li>
            <li class="usa-nav__submenu-item"><a href=""><span>&lt;Navigation link&gt;</span></a></li>
        </ul>
    </li>
    <li class="usa-nav__primary-item">
        <a href="" class="usa-nav-link"><span>FOCUS TO ME</span></a>
    </li>
</ul>
```

Focus on the button with the text "DROPDOWN", open the dropdown, tab over to the button that says "FOCUS TO ME" (without closing the dropdown), then hit the ESC key on the keyboard. Previous to this PR, an error would log in the console. After this PR, no error is logged in the console.

--------

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by mahoneycm** [comment]
@mejiaj I was able to replicate the error on the current build. This PR resolves the error and passes all tests

**Review by mahoneycm — COMMENTED** [review]
@mejiaj I was able to replicate the error on the current build. This PR resolves the error and passes all tests

**Comment by amyleadem** [comment]
This looks good! I performed the following tests successfully:

- [x] When pressing `esc` while focus is on an item inside an open dropdown menu, the focus moves to parent element.
- [x] When pressing `esc` after opening a dropdown and then moving focus to a different top-level nav item, the focus remains on the currently focused item
- [x] When pressing `esc` after opening a dropdown and then moving focus to a different top-level nav item, there are no errors in the console.

Tested in:
- [x] Safari
- [x] Firefox
- [x] Chrome 
- [x] Edge for Mac

**Review by amyleadem — APPROVED** [review]
This looks good. I performed the following tests successfully:

- [x] When pressing `esc` while focus is on an item inside an open dropdown menu, the focus moves to parent element.
- [x] When pressing `esc` after opening a dropdown and then moving focus to a different top-level nav item, the focus remains on the currently focused item
- [x] When pressing `esc` after opening a dropdown and then moving focus to a different top-level nav item, there are no errors in the console.

Tested in:
- [x] Safari
- [x] Firefox
- [x] Chrome 
- [x] Edge for Mac

**Review by mejiaj — APPROVED** [review]
Confirming issue and this fix. 

1. I went to current [develop preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=components-header--default&args=&viewMode=story) on desktop
2. Clicked on a dropdown to expand
3. Tabbed to another nav link
4. Hit <kbd>Escape</kbd> key
5. Saw error in dev tools console
image

---

Followed the same steps on this [branch preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/header-esc-error-fix-4981/iframe.html?id=components-header--default&args=&viewMode=story) without error.

Also tested on mobile, but didn't encounter any issues. Thanks for your contribution @jkjustjoshing!

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
