### PR TITLE
Remove polyfills from USWDS 3

### PR DESCRIPTION
**Pull request by aduth**
## Description

This pull request removes polyfills aimed at supporting Internet Explorer.

## Additional information

Since Internet Explorer is no longer supported, polyfills which exist to add support for the browser should be removed.

**Benefit for users:** USWDS is as lean as it can be to avoid unnecessary excessive load times.
**Benefit for developers:** Fewer dependencies means faster install times and lower surface area risk for security vulnerabilities.

See related browser compatibility:

- [`CustomEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#browser_compatibility)
- [`HTMLElement#hidden`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden#browser_compatibility)
- [`Number.isNaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#browser_compatibility)
- [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#browser_compatibility)
- [`Element#classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#browser_compatibility)
- [SVG external content](https://caniuse.com/mdn-svg_elements_use_external_uri)

Performance comparison:

```
npm run build && du -k dist/js/uswds.min.js && gzip-size dist/js/uswds.min.js
```

- Before: 92kb (24.9kb)
- After: 84kb (23kb gzip)
- Difference: -8kb / -8.7% (-1.9kb / -7.6% gzip)

---

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by aduth** [comment]
On close inspection of our JavaScript bundles, I also noticed that USWDS packages a few additional polyfills transitively through the `receptor` package. I'm not sure how feasible it would be to remove those outside of moving away from the dependency altogether, but worth noting for completeness' sake:

- [`KeyboardEvent#key` polyfill](https://github.com/shawnbot/receptor/blob/de712fd134c5fb1f9c48671579245d58d3296bcd/src/keymap.js#L1)
- [`Object.assign` polyfill](https://github.com/shawnbot/receptor/blob/de712fd134c5fb1f9c48671579245d58d3296bcd/src/behavior.js#L1)
- [`Element#closest` polyfill](https://github.com/shawnbot/receptor/blob/de712fd134c5fb1f9c48671579245d58d3296bcd/src/delegate.js#L2)

**Review by mahoneycm — APPROVED** [review]

**Comment by mahoneycm** [comment]
Accidental approval, flagging for re-review

**Review by mahoneycm — COMMENTED** [review]
This looks good to me!

- [x]  Methods meet baseline requirements
- [x]  All references to polyfills removed
- [x]  No perceived regressions
- [x]  Code meets standards
- [x]  No regression with `Behavior`
    - Spreading the `props` param prevents init issues
- [x]  No regression with `focus-trap`
- [x]  No perceived regressions when installed on site

@aduth can you resolve the merge conflicts when you have the chance?

**Comment by mahoneycm** [comment]
**Question:** Would it be a good idea to remove references to the polyfills from our README ?

https://github.com/uswds/uswds/blob/ae7129cafeeff2089e9ccfd4b286c50e8d7d0b5f/README.md?plain=1#L57

https://github.com/uswds/uswds/blob/ae7129cafeeff2089e9ccfd4b286c50e8d7d0b5f/README.md?plain=1#L515

CC: @mejiaj @amyleadem

**Review by mejiaj — APPROVED** [review]
Thanks for this contribution, it's nice to see these finally getting removed!

### Re: README

@mahoneycm that's a good note. We'll need to update the docs before the official release.

**Review by thisisdano — APPROVED** [review]
Thank you!

**Pull request merged**
