### PR TITLE
Streamlining utilities

### PR DESCRIPTION
**Pull request by thisisdano**
**This PR establishes a baseline set of utilities, based on feedback, modeled after the production utilities from the previous draft. It also builds a toolkit of settings and tools to modify utility class output and fit utilities to your project needs.**

🔒 [Utility docs draft with feedback](https://docs.google.com/document/d/1VsHtYGWyzurwGrOj0S-dMZTgeUnl4xBf3HaajivL9o0/edit#)

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-new-utilities)

---

This work tries to streamline and simplify the conceptual and organizational structure of USWDS utilities in a few ways:
- Utilities are now a **single set**, no longer `prototyping` and `production`
- Utilities are collected and built in a **single stream**, from a single set of rules and a single utilities settings file
- The settings file determines a utility's values and scope options, but all utilities are based on a **common base and modifiers**. (ie all `padding` utilities have a base of `padding` and `t,r,b,l,x,y,[null]` as modifiers)
- Utilities are **customizable** and users are encouraged to modify the utility settings file to fit their project needs and workstyle

## Single set
While users have different needs from their utilities at a prototyping phase and a production phase, it was complicating and potentially confusing to maintain two parallel sets of utilities. This work adds a single new sass file at `src/stylesheets/uswds-utilities.scss` as the base for this single utility stylesheet. Further work could pull these utility styles into the primary `uswds.scss` file, but currently they are separate.

Conceptually, the new utilities are simpler: there are utilities and settings that control their output. All the utilities still draw from the system palette of common values:
- grid
- typescale
- color
- line height
- reading measure
- z-index
- shadow
- opacity

However the subset and expression of those values is now customizable.

## Single stream
This single set only needs a single build stream. Here's how the files are structured:

```
stylesheets/
├── uswds-utilities.scss
├── utilities/
│   ├── _utilities-settings.scss
│   ├── rules/
│   │   ├── [all utility rules...]
│   ├── presets/
│   │   ├── _font-presets.scss
│   │   ├── _settings-presets.scss
│   │   ├── _unit-presets.scss
│   │   ├── colors/
│   │   │  ├── [color presets...]
│   │   │  ├── palettes/
│   │   │  │  ├── _palette-presets.scss
```

- Custom utility properties are set in `utilities/_utilities-settings`
- In `_utilities-settings`, custom utility `value`s can be set manually or with preset groups stored in `presets/` — these settings and values are passed to utility rules
- Rules are the utility-specific data. Each utility has a separate file in `utilities/rules`. Rules collect some static utility data (like the utility's `base` and `modifier`s) and pull in the values from `_utilities-settings`. All this is bundled together passed to the utility builder.

For example, here's the `margin` section of the utility settings.

```sass
/*
========================================
margin
----------------------------------------
usage:
  .margin-[modifier]*-[key]
----------------------------------------
output:
  margin: [value]
----------------------------------------
example:
  .margin-x-auto {
    margin-left: auto;
    margin-right: auto; }

  .margin-g105 {
    margin: .75rem; }
----------------------------------------
*/

$margin-settings: (
  output:       true,
  responsive:   false,
  active:       false,
  focus:        false,
  hover:        false,
  visited:      false,
) !default;

$margin-preset-values: map-collect(
  /*
  $example-preset-1,
  $example-preset-2 [no trailing comma]
  ----------------------------
  $preset-units-px,
  $preset-units-px-negative,
  $preset-units-percentage,
  $preset-units-grid,
  $preset-units-grid-negative,
  $preset-units-ch,
  $preset-units-ch-negative,
  $preset-units-em
  ------------------------- */
  $preset-spacing-tshirt,
  $preset-spacing-negative-tshirt
) !default;

$margin-manual-values: (
  /*
  key:          'value', [trailing comma ok]
  ----------------------------
  [store unused value pairs here]
  ------------------------- */
  0:            '0',
  auto:         'auto',
  1px:          '1px',
  2px:          '2px',
) !default;
```

`$margin-settings` contains the output settings for the utility — whether it's output at all, and if so, what scoped variants should be output as well. Each utility has a settings section.

Almost all the utilities also include values. Values can be added as as prebuilt presets in `$margin-preset-values` or as individual key/pairs in `$margin-manual-values`.

> **Presets** are commonly-used collections of values that allow a user to add groups of values to a utility without adding each specific value manually as a key/value pair.
>
> **Why key/value pairs?** Utilities are constructed in the general form `[base]-[value]`, like `.padding-sm`. When we add values in settings, we have to be able to tell the constructor both the _name_ of the value in the utility name (`sm`) and the _output_ of the value in the final css rule (`4px` if, say, `$spacing-sm: grid(.5)`). This can be a 1:1 relationship, but not always or even often.
>
>Could we modify the builder to accept single values if that 1:1 relationship exists? Maybe! That's a valid idea, but perhaps for another day...

Each preset (`$preset-spacing-tshirt`, `$preset-spacing-negative-tshirt`) is a sass map. For instance:

```sass
$preset-spacing-tshirt: (
  3xs:      $s-spacing-3xs,
  2xs:      $s-spacing-2xs,
  xs:       $s-spacing-xs,
  sm:       $s-spacing-sm,
  md:       $s-spacing-md,
  lg:       $s-spacing-lg,
  xl:       $s-spacing-xl,
  2xl:      $s-spacing-2xl,
  3xl:      $s-spacing-3xl,
);
```

Presets aren't meant to be modified, but the variables referenced in this map are variables set in `stylesheets/settings`. And if any of these are set to `null` the generator will skip them. This way a project can set only the tshirt sizes it needs in `settings` and the generator will adapt the utilities to fit. 

So, `$margin-preset-values` is a collection of sass maps (collected using `map-collect()`), and `$margin-manual-values` is a single sass map. Each of these sections has a commented out space where unused options can be stashed and/or selected.

All these settings maps are bundled together in the utility rule. The master `margin` rule looks like this:

```sass
$margin: (
  margin: (
    base: 'margin',
    modifiers: (
      t: '-top',
      r: '-right',
      b: '-bottom',
      l: '-left',
      y: ('-top', '-bottom'),
      x: ('-left', '-right'),
      noModifier: '',
    ),
    values: map-collect(
      $margin-preset-values,
      $margin-manual-values
    ),
    settings: $margin-settings,
    property: 'margin',
  )
)
```
It sets the utility base (`margin` in this case), the modifiers, collects the values up into a single map, and reads the output settings from the appropriate place in the utility settings file. Some utility rules are a bit more complicated than others, but in general, these are the values passed to the big utility builder in the sky (actually the `@build-utilities-in` mixin found in `functions`).

So the user-flow is:
1. Set your project settings in `settings` (and `variables`, though these should be combined)
2. Use `utility-settings` to determine which utilities are output, and which values they should include.

Users should only modify these settings files, not any of the rules, presets, etc. It keeps the utilities flexible, but somewhat consistent, and helps keep the focus on determining project needs. (Of course, they _could_ write their own presets if they're so inclined, and include them in the utility settings!) 

## Common scope prefixes and base
Since this is a single flow with one coherent set of utilities, there's no longer any reason for the same utility to have a different base if it's being used for prototyping or production. The original draft of these utilities used a verbose format for production utilities and a concise format for prototyping — now we need to pick one or the other.

Scope prefixes scope the class. We currently allow scope to
- responsive breakpoint media queries
- hover state
- active state
- visited state
- focus state

This version uses the state prefix system used by [Tailwind](https://tailwindcss.com/docs/state-variants), with a `:` used to separate them:
- `sm:`, `md:`, `lg:`, `xl:` responsive breakpoint media queries
- `hover:` hover state
- `active:` active state
- `visited:` visited state
- `focus:` focus state

Responsive breakpoints can be mixed with a single additional state as in `lg:hover:background-color-red-50`

Other elements of the utility class are separated by a `-`. Previously the hyphens were omitted if they didn't affect readability. And while that (arguably) results in a cleaner look, that argument didn't hold up to the better argument of simplicity and consistency.

So, the final utility construction looks like 
`namespace` `-` `responsive` `:` `state:` `base` `-` `modifier` `-` `value`

> **What about that namespace prefix?** We set the namespace prefix in `utilities-settings` as `$utilities-namespace-prefix`. The default is `usa-u-` but a developer could change that setting or set it to `null` if it isn't needed.

So what about bases? So what makes a good base? Let's look at these criteria:
- It's determined by a simple, consistent rule
- It's easy to type
- It's easy to read
- It doesn't create contrary or unpleasant connotations

So I evaluated three base naming strategies (🔒[base comparison document](https://docs.google.com/spreadsheets/d/1olVs2UCVVYyp75MOmtOahOt7tY-JDKAIyD4wSAtgnVM/edit?usp=sharing)): 

### full-property-name
-  **rule:** Use the full name of the property
- **exceptions:**  none
- **examples:** 
  - `usa-u-md:font-weight-normal`
  - `usa-u-padding-y-g05`
  - `usa-u-hover:background-blue-50v`
  - `sm:order-first`
  - `margin-x-auto`
  - `lg:hover:box-shadow-1`

| criteria | score | comment |
| --- | --- | --- |
| **simplicity:** | 10 | _As simple as it gets!_ |
| **ease of typing:** | 3 | _This could get tiring. Actually pretty strange to type at first... it feels wrong not to put a colon at the end of the property as you type it. Muscle memory! But with a little time it gels._ |
| **ease of reading:** | 9 | _Easy to read on its own, but could result in extra long classes. Makes markup wonderfully understandable even to a newcomer._ |
| **style:** | 8 | _Resilient, but awkward at the beginning. A grower, though. What it lacks in efficiency of characters, it makes up for in efficiency of thought._ |
| **total:** | **30** ||

### first-character-of-each-word
-  **rule:** Use the first character of each word in the property. If the rule isn't a CSS property, use the entire word. It's OK if some utilities have the same base.
- **exceptions:**  
  - background-color: `bg`
  - max-width: `maxw`
  - max-height: `maxw`
  - min-width: `minw`
  - min-height: `minw`
- **examples:** 
  - `usa-u-md:fw-normal`
  - `usa-u-p-y-g05`
  - `usa-u-hover:bg-blue-50v`
  - `sm:o-first`
  - `m-x-auto`
  - `lg:hover:bs-1`

| criteria | score | comment |
| --- | --- | --- |
| **simplicity:** | 7 | _Pretty simple to go from property to utility_ |
| **ease of typing:** | 9 | _About as concise as it gets. Satisfying to type_ |
| **ease of reading:** | 5 | _Surprisingly easy to understand, especially with the context of a value_ |
| **style:** | 7 | _Familiar to users of other utility frameworks, and pretty efficient_ |
| **total:** | **28** ||

### first-3[4,5]-character
Had so many problems I won't go into it here.

### Conclusions
After some back-and-forth, I'm proposing that we move to the full-property-name format. While there are some realistic developer ergonomics issues with the length of the class, the benefits outweigh the drawbacks. The simplicity, consistency, and readability of this format is undeniable and useful — especially is we consider how many new users (developers, vendors, designers) we expect to come in contact with this system. It's easy to learn, read, and implement. As I've browsed the code of a site that uses this system like [nava.com](https://nava.com) I've very impressed with just how easy it is to understand what's going on just by looking at the markup.

We'll test this and continue, but  I feel good and confident about this direction.

## Customizable
Customization is at the core of this version of the utilities. Where earlier versions asked the user to pick one of two options, this version starts with limited, practical defaults connected to project settings, but is designed to encourage modifications — to adapt the utilities to both project needs and development style.

If anything, it's most similar to [Tailwind](https://tailwindcss.com/), the utility system generator. It shares many of the same principles.

The new `utilities-settings` file allow control over both the output of the utilities, and the values the utilities reference and output. Settings control the following 
- if the utility is output
- if it includes responsive variants
- if it includes state variants: `hover`, `active`, `visited`, and`focus`

Set these values by adding a boolean `true/false` value to the corresponding key in the `$[utility]-settings` map:

```sass
$margin-settings: (
  output:       true,
  responsive:   false,
  active:       false,
  focus:        false,
  hover:        false,
  visited:      false,
) !default;
```

Values set in your project settings affect these outputs. For example, the breakpoints settings in `core/_settings` affect the responsive variants.

Here's what we see in `core/_settings`:

```sass
// Mobile First Breakpoints
$xsmall-screen: null !default;
$small-screen:  481px !default;
$medium-screen: 600px !default;
$large-screen:  1201px !default;
$xlarge-screen: null !default;
```

And here's the corresponding breakpoints preset map in `utilities/presets/_settings-presets`:

```sass
$preset-breakpoints: (
  xs:   $xsmall-screen,
  sm:   $small-screen,
  md:   $medium-screen,
  lg:   $large-screen,
  xl:   $xlarge-screen,
);
```

The preset map isn't meant to be directly modified by the user, but the _variables_ it accepts as values are. If the variable is set to null — as in `$xsmall-screen` and `$xlarge-screen` above — the utility builder will not build a responsive variant for that breakpoint.

#### Using presets in utilities
Presets are collections of values — it's somewhat accurate to think of them as palettes, but it's most accurate to think of them as preset subsets of the master set of available values.

It useful to use the master set of colors as an example. The master set of system colors includes 28 distinct families of color, the colors shown the following diagram, plus `black`, `black-cool`, `black-transparent`, `black-warm`, `white`, `white-transparent`, `white-cool` and `white-warm`.

color-system-wheel

Each of these families has a set of variants from dark to light, and many of them also have vivid variants as well. Altogether, there are hundreds of colors variants available in the master set. It would be cruel and unusual to expect any system user to add these values as individual keypairs: `red-5: $red-5, red-10: $red-10, red-20: $red-20, ...` and so on and so on. So there are a few ways to add these values as preset groups. So how is a preset group constructed?

Let's look at the reds.

reds

The master color palette is static and defined in `/stylesheets/core/_units.scss`. Here's how the red values are set:

```sass
// red
$red-5 :          #fcf5f5;
$red-10:          #f7ddda;
$red-20:          #f7b7ad;
$red-30:          #f28f88;
$red-40:          #ed6b61;
$red-50:          #d83731;
$red-60:          #ab3a3a;
$red-70:          #6e312f;
$red-80:          #3b2523;
$red-90:          #211b1b;
$red-5v:          null;
$red-10v:         #fccec7;
$red-20v:         #fda99c;
$red-30v:         #ff806c;
$red-40v:         #ff5c48;
$red-50v:         #e92106;
$red-60v:         #c31f0a;
$red-70v:         #9c1503;
$red-80v:         #631212;
$red-90v:         null;
```

Each possible red value is set, even if the set value is `null`. (This prevents us from having to add new values to presets if, say a new vivid variant is added.)

I've proposed breaking each color family down in to nine subsets:

| set | values |
| --- | --- |
| `light` | `5`, `10`, `20`, `30` |
| `medium` | `40`, `50`, `60` |
| `dark` | `70`, `80`, `90` |
| `light-vivid` | `5v`, `10v`, `20v`, `30v` |
| `medium-vivid` | `40v`, `50v`, `60v` |
| `dark-vivd` | `70v`, `80v`, `90v` |
| `standard` | `5`, `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90` |
| `vivid` | `5v`, `10v`, `20v`, `30v`, `40v`, `50v`, `60v`, `70v`, `80v`, `90v` |
| `all` | `5`, `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `90` , `5v`, `10v`, `20v`, `30v`, `40v`, `50v`, `60v`, `70v`, `80v`, `90v` |

Color family presets live in `utilities/presets/colors`. Here's how the red presets look in code:

```sass
$preset-colors-red-light: (
  'red-5':  $red-5,
  'red-10': $red-10,
  'red-20': $red-20,
  'red-30': $red-30,
);

$preset-colors-red-medium: (
  'red-40': $red-40,
  'red-50': $red-50,
  'red-60': $red-60,
);

$preset-colors-red-dark: (
  'red-70': $red-70,
  'red-80': $red-80,
  'red-90': $red-90,
);

$preset-colors-red-light-vivid: (
  'red-5v':  $red-5v,
  'red-10v': $red-10v,
  'red-20v': $red-20v,
  'red-30v': $red-30v,
);

$preset-colors-red-medium-vivid: (
  'red-40v': $red-40v,
  'red-50v': $red-50v,
  'red-60v': $red-60v,
);

$preset-colors-red-dark-vivid: (
  'red-70v': $red-70v,
  'red-80v': $red-80v,
  'red-90v': $red-90v,
);

$preset-colors-red-standard: map-collect(
  $preset-colors-red-light,
  $preset-colors-red-medium,
  $preset-colors-red-dark
);

$preset-colors-red-vivid: map-collect(
  $preset-colors-red-light-vivid,
  $preset-colors-red-medium-vivid,
  $preset-colors-red-dark-vivid
);

$preset-colors-red: map-collect(
  $preset-colors-red-standard,
  $preset-colors-red-vivid
);
```

Finally, for completists, all the colors are bundled together as `$preset-colors-all`:

```sass
$preset-colors-all: map-collect(
  $preset-colors-black-cool,
  $preset-colors-black-transparent,
  $preset-colors-black,
  $preset-colors-black-warm,
  $preset-colors-blue,
  $preset-colors-blue-warm,
  $preset-colors-cyan,
  $preset-colors-cyan,
  $preset-colors-gold,
  $preset-colors-green-cool,
  $preset-colors-green,
  $preset-colors-green-warm,
  $preset-colors-indigo-cool,
  $preset-colors-indigo,
  $preset-colors-indigo-warm,
  $preset-colors-magenta,
  $preset-colors-mint-cool,
  $preset-colors-mint,
  $preset-colors-orange,
  $preset-colors-orange-warm,
  $preset-colors-red,
  $preset-colors-violet,
  $preset-colors-violet-warm,
  $preset-colors-white-cool,
  $preset-colors-white-transparent,
  $preset-colors-white-warm,
  $preset-colors-yellow
);
```

So, if you want to add presentational colors to a utility, add the corresponding preset to the `$[utility]-preset-values` map collection:

```sass
$background-color-preset-values: map-collect(
  /*
  $example-preset-1,
  $example-preset-2 [no trailing comma]
  ----------------------------
  [store unused presets here]
  ------------------------- */
  $preset-colors-red-dark,
  $preset-colors-blue-warm-dark,
  $preset-colors-blue-warm-light,
  $preset-colors-black-cool-dark,
  $preset-colors-red-medium-vivid
) !default;
```

#### Preset palettes
**Preset palettes** combine colors from different families and live in `utilities/presets/colors/palettes/_palette-presets.scss`. Preset palettes are a powerful idea. They help  create useful subsets of the master color set connected to different themes, or tonal effects. This idea isn't fully implemented in this iteration, but the idea is as follows:
- We (and others) can build presentational palettes around useful color sets and combinations
- We (and others) can build semantic (or _abstracted_) themes connected to the semantic color theme names we set in settings
- Color theme palettes could be shared through our website or github to assist or inspire new project teams

The implementation of this is still quite raw. For instance, here's a simple grayscale presentational palette:

```sass
$preset-palette-grayscale: map-collect(
  $preset-colors-black,
  $preset-colors-white
);
```

But where this really gets powerful is how it intersects with project settings. Here's a more complicated palette tied to the current USWDS color variables: 

```sass
$preset-palette-project-settings: (
  primary:                  $color-primary,
  primary-darker:           $color-primary-darker,
  primary-darkest:          $color-primary-darkest,
  base:                     $color-base,
  primary-alt:              $color-primary-alt,
  primary-alt-darkest:      $color-primary-alt-darkest,
  primary-alt-dark:         $color-primary-alt-dark,
  primary-alt-light:        $color-primary-alt-light,
  primary-alt-lightest:     $color-primary-alt-lightest,
  secondary:                $color-secondary,
  secondary-darkest:        $color-secondary-darkest,
  secondary-dark:           $color-secondary-dark,
  secondary-light:          $color-secondary-light,
  secondary-lightest:       $color-secondary-lightest,
  gold:                     $color-gold,
  gold-light:               $color-gold-light,
  gold-lighter:             $color-gold-lighter,
  gold-lightest:            $color-gold-lightest,
  green:                    $color-green,
  green-light:              $color-green-light,
  green-lighter:            $color-green-lighter,
  green-lightest:           $color-green-lightest,
  blue:                     $color-blue,
  blue-light:               $color-blue-light,
  blue-lighter:             $color-blue-lighter,
  blue-lightest:            $color-blue-lightest,
  gray:                     $color-gray,
  gray-dark:                $color-gray-dark,
  gray-light:               $color-gray-light,
  gray-lighter:             $color-gray-lighter,
  gray-lightest:            $color-gray-lightest,
  gray-warm-dark:           $color-gray-warm-dark,
  gray-warm-light:          $color-gray-warm-light,
  gray-cool-light:          $color-gray-cool-light,
  focus:                    $color-focus,
  visited:                  $color-visited,
);
```
These variables reference the project settings in `_variables.scss`!

```sass
 // Color
$color-blue:                 $blue-70 !default;
$color-blue-darker:          $blue-warm-70v !default;
$color-blue-darkest:         $blue-warm-80v !default;
$color-blue-light:           $blue-warm-50 !default;
$color-blue-lighter:         $blue-warm-30 !default;
$color-blue-lightest:        $blue-warm-10 !default;

$color-aqua:                 $cyan-30v !default;
$color-aqua-dark:            $cyan-40v !default;
$color-aqua-darkest:         $blue-60 !default;
$color-aqua-light:           $cyan-20 !default;
$color-aqua-lightest:        $cyan-5 !default;

$color-red:                  $red-50 !default;
$color-red-dark:             $red-60v !default;
$color-red-darkest:          $red-70v !default;
$color-red-light:            $red-30 !default;
$color-red-lightest:         $red-10 !default;

$color-white:                $white-0 !default;
$color-black:                $black-100 !default;
$color-black-light:          $black-90 !default;

$color-gray-dark:            $black-cool-80 !default;
$color-gray:                 $black-cool-60 !default;
$color-gray-medium:          #757575 !default;
$color-gray-light:           $black-30 !default;
$color-gray-lighter:         $black-cool-10 !default;
$color-gray-lightest:        $black-cool-5 !default;

$color-gray-warm-dark:       $black-warm-70 !default;
$color-gray-warm-light:      $black-warm-10 !default;
$color-gray-cool-light:      $blue-warm-5 !default;

$color-gold:                 $gold-20v !default;
$color-gold-light:           $gold-10v !default;
$color-gold-lighter:         $yellow-10 !default;
$color-gold-lightest:        $gold-5 !default;

$color-green:                $green-cool-50 !default;
$color-green-light:          $green-cool-40 !default;
$color-green-lighter:        $green-cool-20 !default;
$color-green-lightest:       $green-cool-5 !default;

$color-cool-blue:            #205493 !default;
$color-cool-blue-light:      #4773aa !default;
$color-cool-blue-lighter:    #8ba6ca !default;
$color-cool-blue-lightest:   #dce4ef !default;

$color-purple:               $violet-70v !default;

// Functional colors
$color-primary:              $color-blue !default;
$color-primary-darker:       $color-blue-darker !default;
$color-primary-darkest:      $color-blue-darkest !default;

$color-primary-alt:          $color-aqua !default;
$color-primary-alt-dark:     $color-aqua-dark !default;
$color-primary-alt-darkest:  $color-aqua-darkest !default;
$color-primary-alt-light:    $color-aqua-light !default;
$color-primary-alt-lightest: $color-aqua-lightest !default;

$color-secondary:            $color-red !default;
$color-secondary-dark:       $color-red-dark !default;
$color-secondary-darkest:    $color-red-darkest !default;
$color-secondary-light:      $color-red-light !default;
$color-secondary-lightest:   $color-red-lightest !default;

$color-base:                 $color-black-light !default;
$color-focus:                $color-gray-light !default;
$color-visited:              $color-purple !default;

$color-shadow:               $black-transparent-30 !default;
$color-transparent:          rgba(#000, 0) !default;
```

That's based on the following conversion:

uswds-color-conversion

Now, the way all these are set, named, and referenced is a topic for later discussion — but it suggests a pathway for theming and using consistent colors in the system, and potentially a way to present and share themes/palettes!

#### Unit presets
The preset idea applies equally to fonts and other unit values referenced in the utilities.

For instance, the `margin` utility can accept a number of different units of whitespace, and our guidance should recommend something like
- pixel units
- negative pixel units
- grid units
- negative grid units
- project whitespace settings

Each of these units is collected into a preset. Grid unit presets look like this:

```sass
$preset-units-grid-small: (
  'g05':    $u-spacing-05,
  'g1':     $u-spacing-1,
  'g105':   $u-spacing-105,
  'g2':     $u-spacing-2,
);

$preset-units-grid-medium: (
  'g205':   $u-spacing-205,
  'g3':     $u-spacing-3,
  'g4':     $u-spacing-4,
  'g5':     $u-spacing-5,
);

$preset-units-grid-large: (
  'g6':     $u-spacing-6,
  'g7':     $u-spacing-7,
  'g8':     $u-spacing-8,
  'g9':     $u-spacing-9,
  'g10':    $u-spacing-10,
);

$preset-units-grid-xlarge: (
  'g15':    $u-spacing-15,
  'g20':    $u-spacing-20,
  'g25':    $u-spacing-25,
  'g30':    $u-spacing-30,
  'g40':    $u-spacing-40,
  'g50':    $u-spacing-50,
);

$preset-units-grid-small-negative: (
  'ng05':   -#{$u-spacing-05},
  'ng1':    -#{$u-spacing-1},
  'ng105':  -#{$u-spacing-105},
  'ng2':    -#{$u-spacing-2},
);

$preset-units-grid-medium-negative: (
  'ng205':  -#{$u-spacing-205},
  'ng3':    -#{$u-spacing-3},
  'ng4':    -#{$u-spacing-4},
  'ng5':    -#{$u-spacing-5},
);

$preset-units-grid-large-negative: (
  'ng6':    -#{$u-spacing-6},
  'ng7':    -#{$u-spacing-7},
  'ng8':    -#{$u-spacing-8},
  'ng9':    -#{$u-spacing-9},
  'ng10':   -#{$u-spacing-10},
);

$preset-units-grid: map-collect(
  $preset-units-grid-small,
  $preset-units-grid-medium,
  $preset-units-grid-large,
  $preset-units-grid-xlarge
);

$preset-units-grid-negative: map-collect(
  $preset-units-grid-small-negative,
  $preset-units-grid-medium-negative,
  $preset-units-grid-large-negative
);
```

Similarly to colors, if you want to add presentational unit values to a utility, add the corresponding presets to the `$[utility]-preset-values` map collection:

```sass
$margin-preset-values: map-collect(
  /*
  $example-preset-1,
  $example-preset-2 [no trailing comma]
  ----------------------------
  [store unused presets here]
  ------------------------- */
  $preset-units-px,
  $preset-units-px-negative,
  $preset-units-grid,
  $preset-units-grid-negative,
) !default;
```

Settings whitespace presets work the same way, referencing the whitespace tshirt sizing set in settings. (And, just as before, if a size is set to `null` in  settings, that value will be excluded from the utility builder):

```sass
$s-spacing-3xs:           null !default;
$s-spacing-2xs:           null !default;
$s-spacing-xs:            $u-spacing-05 !default;
$s-spacing-sm:            $u-spacing-1 !default;
$s-spacing-md:            $u-spacing-2 !default;
$s-spacing-lg:            $u-spacing-3 !default;
$s-spacing-xl:            $u-spacing-4 !default;
$s-spacing-2xl:           $u-spacing-5 !default;
$s-spacing-3xl:           $u-spacing-9 !default;
```
```sass
$preset-spacing-tshirt: (
  3xs:      $s-spacing-3xs,
  2xs:      $s-spacing-2xs,
  xs:       $s-spacing-xs,
  sm:       $s-spacing-sm,
  md:       $s-spacing-md,
  lg:       $s-spacing-lg,
  xl:       $s-spacing-xl,
  2xl:      $s-spacing-2xl,
  3xl:      $s-spacing-3xl,
);

$preset-spacing-tshirt-negative: (
  nxs:       -#{$s-spacing-xs},
  nsm:       -#{$s-spacing-sm},
  nmd:       -#{$s-spacing-md},
);
```

Include these in the `$[utility]-preset-values` map collection as `$preset-spacing-tshirt` and `$preset-spacing-tshirt-negative`

#### Font presets
Font presets are more complicated and more of a work in progress right now. 

The complete issues involved with fonts and normalization are a topic for a subsequent issue and PR, but the gist is that for [reasons; mostly to do with progressive enhancement, resilience, and modularity] the `font` utility combines the ideas of `font-family` and `font-size`: resulting in a utility like `font-sans-xl`.

So, to build this utility, there are two dependencies:
- Does the requested font family (ie `sans`) exist in this project?
- Does the requested font size (ie `xl`) exist in this project?

The builder makes that determination based on the variables set in both `settings` and `variables`.

It uses the font sizes from `settings`...
```sass
$s-font-size-3xs:         $u-type-scale-12 !default;
$s-font-size-2xs:         $u-type-scale-14 !default;
$s-font-size-xs:          $u-type-scale-16 !default;
$s-font-size-sm:          $u-type-scale-17 !default;
$s-font-size-md:          $u-type-scale-18 !default;
$s-font-size-lg:          $u-type-scale-24 !default;
$s-font-size-xl:          $u-type-scale-32 !default;
$s-font-size-2xl:         $u-type-scale-40 !default;
$s-font-size-3xl:         null !default;
```

... and the font families from `variables`:
```sass
$font-sans:           'Source Sans Pro', $helvetica !default;
$font-serif:          null !default;
$font-mono:           'Roboto Mono', $monospace !default;
$font-cond:           null !default;
```

Then, for each non-null font family, it'll build a variation for each non-null font size.

Each individual font rule is more complicated than a simple keypair, it's its own map:

```sass
$preset-mono-3xs: (
  mono-3xs: (
    slug: 'mono-3xs',
    content: $s-font-size-3xs,
    extends: font-mono,
    dependency: $font-mono,
  ),
);
```

For the final CSS rule `.[utilitySuffix] { font-size: [size]; font-family: [family] }`

This map tells the builder
- the name of the [utilitySuffix] to append to the utility selector: `slug`
- the [size] used in the font-size declaration: `content`
- the additional condition required to output: `dependency`
- the font-family rule this utility rule should extend (to avoid a separate multiple font-family rule for each font utility): `extends`

There is a rule map like the above for each font family variant and size, bundled together by family and then all together:

```sass
$preset-mono-tshirt: map-collect(
  $preset-mono-3xs,
  $preset-mono-2xs,
  $preset-mono-xs,
  $preset-mono-sm,
  $preset-mono-md,
  $preset-mono-lg,
  $preset-mono-xl,
  $preset-mono-2xl,
  $preset-mono-3xl
);
```
```sass
$preset-font-tshirt: map-collect(
  $preset-mono-tshirt,
  $preset-sans-tshirt,
  $preset-serif-tshirt
);
```

This preset can be added to the `font` utility setting:
```sass
$font-preset-values: map-collect(
  /*
  $example-preset-1,
  $example-preset-2 [no trailing comma]
  ----------------------------
  [store unused presets here]
  ------------------------- */
  $preset-font-tshirt
) !default;
```

There are also font presets for each face in each of the 20 steps in the master font scale as well. All these presets are stored in `utilities/presets/_font-presets.scss`. There's still more work to do on these! Please stay tuned!

#### Conclusion
The relationship between palettes, variables, settings, and utilities is the stylistic backbone of the system. **It will be critical to do a good job documenting and communicating how it all works together.** This PR can serve as a first draft of that communication. There's a lot still to do, but I'm very confident in the flexibility and power of this system. I feel very excited about settings and palettes, and how they could be shared and used for guidance.

### CODE REVIEW

**Comment by maya** [comment]
@thisisdano the grid doesn't seem to be working anymore: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-new-utilities/components/detail/grid--default.html can this be fixed?

**Comment by maya** [comment]
[Tables](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-new-utilities/components/detail/tables.html) are incorrectly styled, issues with the border (too thick):

screen shot 2018-03-29 at 11 16 13 am

**Comment by maya** [comment]
The [warning info box](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-new-utilities/components/detail/alerts--warning.html) seems to be much lighter than the original and much light compared to the other boxes.

Before 
screen shot 2018-03-29 at 11 19 35 am

After
screen shot 2018-03-29 at 11 19 30 am

**Comment by maya** [comment]
Is this up to date with the `develop` branch? Want make sure it works with the new build steps and to see if it saves time?

**Comment by thisisdano** [comment]
OK — I'm going to merge this, then dig into these issues. Hopefully that'll assure I only have to fix them once.

**Pull request merged**
