### PR TITLE
USWDS - Select: Multiple select overflow

### LINKED ISSUE #5047: USWDS - Bug: Multiple Select (component) option text overflow
### Describe the bug

When the Select component has the multiple attribute set and options with text longer than the Select width, selected options overflow their highlight when the field loses focus. This is a minor interface issue and does not impact the functioning of the component.

### Steps to reproduce the bug

1. Add a select component with the multiple attribute set and an option with text that is longer than the default select width.
2. Highlight the long text option
3. Remove focus from select

### Expected Behavior

The highlight should span the full Select width (preferable) or the text should remain cropped when the Select loses focus.

### Related code

_No response_

### Screenshots

image

image

### System setup

USWDS 3.3.0

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

**Added ellipses to multiple select overflow.** This provides a clear indication to users that there is text being cut off by the select width.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5047 

## Related pull requests

[Site Changelog PR](https://github.com/uswds/uswds-site/pull/2080)

## Preview link

[Multiple select →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-multiple-select-overflow/iframe.html?args=&id=components-form-inputs-select--multiple&viewMode=story)

## Problem statement

Multiple select cuts off long options on Safari & Firefox due to browser styles changing the text color to white, and additional padding leftover from the single select's dropdown icon

## Solution

Unfortunately, there is no way to wrap option text within a select element at this time. Instead, the component should convey that there is additional text not visible to the user. This will provide a better user experience for all multiple select users.

This still isn't ideal for users and developers should focus on allowing options to be completely visible within their selects by either increasing the select element width or using short, concise options.

## Testing and review

1. Visit multiple select story in Safari or Firefox
2. View the longer `Option C` 
3. Confirm ellipses are visible
4. Select option C
5. Confirm no information loss due to padding or text color change

### Before

**Chrome:**
image

**Firefox**
image

**Safari**
image

### After

**Chrome:**
image

**Firefox**
image

**Safari**
image

- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm run prettier:scss` to format any Sass updates.
- [x] Run `npm test` and confirm that all tests pass.

### CODE REVIEW

**Review by amyleadem — CHANGES_REQUESTED** [review]
@mahoneycm, this seems to resolve the issue, but unfortunately I was not able to see the ellipsis on Safari. I've added some notes below.

Here are some of the things I tested:
- [ ] On init, confirm ellipsis is present on long option text
    - I do not see the ellipsis in Safari. I do see the ellipsis in Firefox and Chrome.
    Safari (initialized):
    image
- [ ] On focus, confirm background color extends the full width of the input
    - In Safari, the background does not extend the full-width of the text. Chrome and Firefox look good. 
    image
    image
- [x] Confirm screen reader reads entire text
- [x] Tested on Firefox, Safari, Chrome
    - Note, there is some behavior in Firefox that I didn't expect, but it _appears_ to be native behavior in select boxes with `overflow-x: hidden` options. 
        - If I hit tab once, focus moves to the entire input (Expected)
        - If I hit tab again while focus is on the input, it focuses on the option with overflow text. (Not expected, for me at least)
        - Some quick testing revealed that this happens in non-USWDS/standard multiple select boxes as well. Not sure if there is any action that can be taken here, just wanted to flag it in case anyone else noticed or if there is a workaround.

**Comment by mahoneycm** [comment]
## Update

### Elipsis on Safari

Unfortunately, it looks like Safari doesn't support `text-overflow: ellipsis` on `<option>` tags. I looked around for solutions and tried playing with it myself for a while but it doesn't seem possible without JS.

We can either remove it so it's consistent across the board or keep it for Chrome and Firefox

### Removed all of the right-side padding

Now that we can't rely on the ellipses to stop the text from reaching the edge, I've removed the right side padding completely to allow the focus background to reach the edge of the select element.

**Results:**

Chrome:
image

Safari:
image

### Resolved Firefox keyboard behavior

Switching `overflow-x` to `overflow`. This resolved the tabbing issue where Firefox would target overflow options after targetting the select box itself

**Comment by mahoneycm** [comment]
@mejiaj @amyleadem Bumping for re-review once you all have availability after `3.5.0` work!

**Review by amyleadem — APPROVED** [review]
Looks good to me! I performed the following tests:
- [x] Move focus to the long text option item -  Confirm content and background color extends the full width of the input
- [x] Select the long text option item by moving focus to it then move focus out of the component  - Confirm that the background color shows behind only the selected text and that the background color extends the full width of the input
- [x] Tested on Firefox, Safari, Chrome

**Comment by mahoneycm** [comment]
@mejiaj bumping for review !

**Comment by mahoneycm** [comment]
@mejiaj It does result in odd styles for Safari

image


image

**Review by mejiaj — APPROVED** [review]
PR description is accurate & up-to-date. Approved!

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
