### PR TITLE
[usa-header] Focus "Menu" button when hitting "ESC" key

### LINKED ISSUE #4982: [usa-header] Hitting "ESC" in mobile global nav doesn't bring focus back to "Menu" button
### Describe the bug

Focus does not always come back to the "Menu" button when the global mobile navigation is closed with the "ESC" key.

### Steps to reproduce the bug

1. Go to [this demo site](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=components-header--default&args=&viewMode=story)
2. Make browser a mobile width
3. Tab to "Menu" button and hit "enter" to open the side nav
4. Tab down to one of the nav items in the list
5. Hit the "ESC" key

### Expected Behavior

Expected behavior: The keyboard focus goes to the "Menu" button to re-open the nav
Current behavior: The keyboard focus isn't brought back to any specific element, falling back to browser default behavior when the item you're focusing on is made `display: none`.

### Related code

_No response_

### Screenshots

image
image

### System setup

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by jkjustjoshing**
## Description

When the mobile nav is open, hitting the "ESC" key should focus on the "Menu" button to re-open the menu.
resolves #4982

## Additional information

This seems like intended behavior that's not working correctly now.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by mahoneycm — COMMENTED** [review]
@mejiaj same fix found in #4981

**Review by mahoneycm — COMMENTED** [review]
@mejiaj Works great!

**Comment by jkjustjoshing** [comment]
Ah shoot I mean to exclude the commit for #4981 from this PR so you could decide on them separately. Would you like me to remove the commit in #4981 from this PR to review separately? If you plan on accepting both then it might be simpler to just close the other PR and merge only this one. Happy to modify the PR in whatever way makes the most sense.

**Comment by mejiaj** [comment]
@jkjustjoshing could you remove the extra commit from the other PR? 

While having both in a single PR would be convenient, it might be better for historical reference to isolate each problem to their own PR.

**Comment by jkjustjoshing** [comment]
Code that wasn't supposed to be in this PR has been removed!

**Review by amyleadem — APPROVED** [review]
Important improvement! I performed the following tests successfully:
- [x] When pressing `esc` while focus is on the close button of the expanded menu, the menu closes and focus moves to the menu button.
- [x] When pressing `esc` while focus is on an item inside the open menu, the menu closes and focus moves to the menu button.

Tested in:
- [x] Safari
- [x] Firefox
- [x] Chrome
- [x] Edge for Mac

**Comment by jkjustjoshing** [comment]
Awesome @amyleadem, glad it looks good!

If you don't mind, would you be willing to add a `hacktoberfest-accepted` label to this PR?

**Review by mejiaj — APPROVED** [review]
Tested all mobile variants of header without any console errors or visual regressions. Created local branch [`jkjustjoshing-bugfix/4982-menu-focus`] in repo for testing and generating preview.

**Preview links**
- [Header default](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jkjustjoshing-bugfix/4982-menu-focus/iframe.html?args=&id=components-header--default&viewMode=story)
- [Megamenu](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jkjustjoshing-bugfix/4982-menu-focus/iframe.html?args=&id=components-header--megamenu&viewMode=story)
- [Extended](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jkjustjoshing-bugfix/4982-menu-focus/iframe.html?args=&id=components-header--extended&viewMode=story)
- [Extended megamenu](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jkjustjoshing-bugfix/4982-menu-focus/iframe.html?args=&id=components-header--extended-megamenu&viewMode=story)

---

Thanks for the contribution and for updating the unit test!

**Comment by thisisdano** [comment]
Thank you!

**Pull request merged**
