### PR TITLE
Internal: GitHub Workflows security hardening

### PR DESCRIPTION
**Pull request by thisisdano**
Internal clone of https://github.com/uswds/uswds/pull/4960 for final scans and testing

### CODE REVIEW

**Comment by amyleadem** [comment]
@thisisdano 
I was able to check the updated permissions for the `add-to-project` action in my personal repo and the action continued to work as expected. The codeQL updates seem to align with guidance and it looks like the scan is working. Do you need me to take any additional action on that?

**Comment by thisisdano** [comment]
No further actions, but if you could approve this PR that's all that remains!

**Comment by mejiaj** [comment]
Closed with https://github.com/uswds/uswds/pull/4960.

**Comment by thisisdano** [comment]
@mejiaj I think this was closed by mistake. It's an internal clone of https://github.com/uswds/uswds/pull/4960 and still needs to be reviewed, approved, and merged

**Comment by amyleadem** [comment]
Apologies, I missed the approval comment from before. I'll take another look at this PR now.

**Review by amyleadem — APPROVED** [review]
Looks good to me. 
[x] Re-confirmed in a personal repo that adding `permissions: { }` to `add-to-project.yml` works as expected
[x] Confirmed that CodeQL needs `security-events: write` (Reference: [CodeQL readme](https://github.com/github/codeql-action/blob/main/README.md?plain=1#L47))

**Pull request merged**
