### PR TITLE
USWDS - Footer: Remove additional space. Fixes #5214 (Bug)

### LINKED ISSUE #5214: USWDS - Bug: Agency contact center in the footer component is not right-aligned in the grid
### Describe the bug

The grid gap classes on that part of the footer cause a space on the right that misaligns what seems to be right-justified content and causes it to misalign from the grid. This misalignment becomes apparent if you have other right-justified content close-by:

Screen Shot 2023-04-05 at 10 09 33 AM

An easy fix that worked for me is to remove `mobile-lg:grid-gap-2` on .usa-footer__logo and set the distance between the agency logo and title through CSS margin instead:

Screen Shot 2023-04-05 at 10 09 33 AM

I also removed the grip-gap on the parent grid-row in that usa-footer__secondary-section, but mileage could vary by use-case (in other word, some more work could be needed to fully align content in that section of the footer)

 

### Steps to reproduce the bug

1. Examine the alignment of the Agency section of the footer with the grid, specifically on the right side.

### Expected Behavior

I expect the 'Agency Contact' section that is comprisd of the social nav, Agency Contact Center header and agency contact info to be right justified and align with the grid on the right.

### Related code

_No response_

### Screenshots

Screen Shot 2023-04-05 at 10 16 43 AM
Screen Shot 2023-04-05 at 10 09 33 AM

### System setup

- 3.4.1
- OS
- Chrome

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by danbrady**
# Summary

**Fix alignment in Footer** Removes additional space that prevents the correct right alignment of elements.

## Breaking change

This is not a breaking change.

## Related issue

Resolves #5214

## Preview link

Current state:
image

Proposed fix:
image

## Problem statement

Additional padding on right side of footer within the secondary section could cause misalignment with other sections.

## Solution

Modified HTML structure to use a layout that prevents additional padding/space. (No new styles/classes created.)

## Testing and review

1. Update was validated in browser across all breakpoint views
2. Additional validation of correct layout across all breakpoints/platforms would be good! Or please let me know if there is automated visual regression testing that I should be using :)

### CODE REVIEW

**Review by mejiaj — COMMENTED** [review]
Looks like the issue is coming from the nested grid row's. Specifically `.usa-footer__logo.grid-row.mobile-lg:grid-col-6 mobile-lg:grid-gap-2`.

Maybe we should consider simplifying the markup by removing the grid rows for footer logo, social logos, and addresses. I know we kept the grid classes in Banner rework #5000, but there's a lot more here so worth removing.

**Review by mahoneycm — COMMENTED** [review]
@mejiaj Going off of your comment, it looks like there are margins being set by `.grid-row.grid-gap>*` that is causing that space on the right.

Should we consider this a breaking change because we're editing markdown?

**Comment by mejiaj** [comment]
> @mejiaj Going off of your comment, it looks like there are margins being set by `.grid-row.grid-gap>*` that is causing that space on the right.
> 
> Should we consider this a breaking change because we're editing markdown?

Yes, it'd be a breaking change because of markup. I've added the `Needs: discussion` tag to the original issue, so we can discuss before making the change.

**Comment by danbrady** [comment]
Happy to tackle simplifying the HTML/CSS upon your discussion. Let me know if we'd like to remove the grid utilities on just the sections @mejiaj mentioned, or the whole component. (Or any other requirements that emerge.)

**Comment by mejiaj** [comment]
@danbrady after discussing with the team let's move forward with removing grid classes from component ― starting with the problematic areas.

**Comment by danbrady** [comment]
@mejiaj To confirm, the goal for the next step is to remove all grid classes from problem areas (footer logo, social logos, and addresses) and get equivalent layout using flex utilities, but leave the grid classes (and `usa-layout-grid` package) in for the rest of the footer(s)?

**Comment by mejiaj** [comment]
@danbrady sorry I missed this message. 

Yes, we're keeping grid classes (to prevent breaking change), but removing the grid layout dependency in SASS.

**Comment by danbrady** [comment]
No problem, @mejiaj! That's the direction I took. I have a WIP PR (#5289) for removing the grid dependency but need some guidance, when you have the chance. I'll tag you for review. Thanks!

**Comment by danbrady** [comment]
This updates the markup to remove the errant space defined in the issue. I've updated the markup, but only to use existing classes so I don't believe it's a breaking change? Thanks!

**Comment by mahoneycm** [comment]
Hey there @danbrady!

Any changes to component markup are considered breaking changes because they require users to manually update the markup in their component code.

It'd probably be a better idea to return to a scss based solution for this one.

**Review by mejiaj — CHANGES_REQUESTED** [review]
@danbrady thanks for creating this. 

As @mahoneycm's mentioned; any markup changes would be considered breaking. Would you be able to follow his suggestion and use a SCSS-based approach?

**Comment by danbrady** [comment]
Hi @mahoneycm / @mejiaj!  Sure, I'll take a look and see if we can fix it with SCSS alone and not change any markup. We'll probably have to override grid/flex classes for this case.

So I understand for next time, can you explain to me why this instance would be a breaking change? I understand that if a user updates markup and it refers to updated CSS that hasn't been published it would actually break a component. However, while this change does change the markup, it only changes markup that refers to existing/unchanged styles. If it doesn't reference any new or changed classes, the change should operate ok whether the user updates the markup or not, no? 

(BTW, I'm not disagreeing. Just want to learn :)

**Comment by mejiaj** [comment]
@danbrady historically these types of changes bring difficulties to users, especially those on small teams trying to stay up-to-date with USWDS.

We're working on improving how we communicate breaking changes & how we can make upgrading easier. In the meantime, we're trying to avoid changing markup.

**Review by mejiaj — APPROVED** [review]

**Review by mahoneycm — APPROVED** [review]
Short and effective! Love to see it. Thanks @danbrady ! Looks great

**Review by thisisdano — APPROVED** [review]
Nice scoped fix

**Pull request merged**
