### PR TITLE
USWDS - Combobox: Keyboard selection compliance update. Resolves #5161

### LINKED ISSUE #1898: Publish NPM

### LINKED ISSUE #5161: USWDS-Site - Bug: ComboBox
## Finding an Option from the Combobox List

- Keyboard users (especially those using  AT) expect to be able to type the same character to navigate through all options starting with the same letter (example: type “S” multiple times to move through “South Carolina” followed by “South Dakota”, etc.)

https://user-images.githubusercontent.com/4629398/201210932-e176b55e-1de1-4dfe-83ac-fed69f7b9496.mp4

## Selecting a Combobox Option

- Combobox allows users to confirm a selection using either the ENTER key (which is good) or the TAB key (which is unexpected behavior).
- Additionally, the SPACE key (often used to confirm selections) only scrolls down the Combobox list.

https://user-images.githubusercontent.com/4629398/201208845-ee10feaf-619e-4b44-b6ac-c23bdaecf6d6.mp4

https://user-images.githubusercontent.com/4629398/201209724-b3f96054-5d90-42f1-98f0-53297e4165a4.mp4

## Finding an Option from the Combobox List

1. Turn on screen reader
2. Keyboard navigation to the Combobox input
3. Type a alphabetical letter to get to an item i.e. `S` for _South Carolina_
4. Repeat typing the same letter
5. FAIL

## Selecting a Combobox Option via spacebar

1. Turn on screen reader
2. Keyboard navigation to the Combobox input
3. Use arrow keys to navigate to an item
4. Type spacebar to select the item
5. FAIL

## Selecting a Combobox Option via tab
1. Turn on screen reader
2. Keyboard navigation to the Combobox input
3. Use arrow keys to navigate to an item
4. Type tab to move focus from the field
5. FAIL

## Finding an Option from the Combobox List

Users working with AT expected to be able to type the same character to navigate through all options starting with the same letter (example: type “S” multiple times to move through “South Carolina” followed by “South Dakota”, etc.)

## Selecting a Combobox Option or tab

- Combobox allows users to confirm a selection using either the ENTER key (which is good) or the TAB key (which is unexpected behavior).
- Additionally, the SPACE key (often used to confirm selections) only scrolls down the Combobox list.

### Screenshots

_No response_

### System setup

OS: MacOS: 12.6 Monterey
Browser: Safari 16.1 (17614.2.9.1.13, 17614)
Voiceover and keyboard

### Additional context

On videos above, the green text indicates the keyboard inputs.
cc: @jonadecker @steveja11y 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mahoneycm**
## Summary
Updates Combobox JS to allow Tab and Spacebar keyboard inputs to operate as expected within combobox drowdowns

## Breaking change
This is **potentially** a breaking change if developers instruct users to make a selection via tab.

## Related issue
Closes [USWDS-Site uswds/uswds#5161](https://github.com/uswds/uswds/issues/5161)

## Preview link
[Combobox →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-combobox-tab-space-fix/iframe.html?args=&globals=&id=components-form-inputs-combo-box--default&viewMode=story)

## Problem statement
Keyboard users should expect consistent behaviour when navigating with a combobox component. Users should be able to use `Tab` to escape the combobox selection without making a choice, and `Space` to select the current highlighted option when within the dropdown menu.

Currently, we include JS that captures the tab event and uses it to select a highlighted combobox option instead of escaping the element.

Pressing the spacebar currently causes the combobox to scroll, rather than selecting the highlighted element as expected.

## Solution
I've replaced the Tab functionality with the Spacebar. Now both elements behave as expected when within the combobox dropdown menu

## Testing and review
1. The combobox story or a page with a combobox component
2. Navigate to the component using your keyboard
3. Use the up and down arrows to make a selection
4. Press tab to escape the combobox
5. Check that the combobox is no longer selected and that no selection was made
6. Return to the combobox and repeat step 3
7. Press the spacebar
8. Check that a selection was made

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm test` and confirm that all tests pass.

### CODE REVIEW

**Comment by mahoneycm** [comment]
Issue transferred to USWDS Repo! Thanks for the tip @amyleadem  🥇

**Review by mejiaj — APPROVED** [review]
Looks good! I didn't encounter any issues with selecting items from the dropdown box via <kbd>Spacebar</kbd>. I also tested usa-time-picker as well because it relies on combobox and everything looked good there.

Thanks for updating the unit test too!

---

BTW, you don't need to add `Resolves #` in the PR title as long as you have it in the body.

**Review by amyleadem — APPROVED** [review]
Nice fix! 
I was able to successfully perform the following tests:
- [x] Run `npm start`, `npm test` , `npm run lint`, `npm run prettier:js` without error
- [x] Confirm that `tab` closes the combo box and moves focus to the next element
- [x] `shift` + `tab` moves focus to the combo box input
- [x] Confirm that `space` selects an item
- [x] Confirm that `enter` selects an item
- [x] Confirm that `esc` closes the combo box and keeps focus on combo box
- [x] Confirm that typing letters opens combobox and filters relevant selections
- [x] Confirm that VoiceOver reads as expected
- [x] Confirm these same behaviors in Time picker
- [x] Test keyboard/touch interaction in Safari, Firefox, Chrome, Edge, iOS

**Comment by thisisdano** [comment]
I'll draw up a changelog PR for this change

**Comment by thisisdano** [comment]
Note that this resolves two of the issues in https://github.com/uswds/uswds/issues/5161 but not the `type the same character to navigate through all options starting with the same letter` issue, which I'm inclined to categorize as a feature request and not a bug. We should adapt https://github.com/uswds/uswds/issues/5161 into a new feature request and close the original issue with this PR.

**Pull request merged**
