### PR TITLE
3774 - Summary box version 1

### PR DESCRIPTION
**Pull request by 3DX8**
## Description

Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Please also link to the GitHub issue it resolves.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [X] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [X] Run `npm test` and make sure the tests for the files you have changed have passed.
- [X] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [X] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by 3DX8** [comment]
@ardenk @jaredcunha Here are the previews:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box--default.html

https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box--success.html

https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box--warning.html

https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box--error.html

Not sure if the Summary box examples should be named by the class names (info, success etc..). FYI, The backgrounds are the "lighter" version of the colors and the borders are the actual colors corresponding to the class names:

Blue
background: info-lighter
border: info

Green
background: success-lighter
border: success

Yellow
background: warning-lighter
border: warning

Red
background: error-lighter
border: error

Looking forward to feedback, thanks!
Mitch

**Comment by ardenk** [comment]
@3DX8 There should not be success, warning, or error states for this. Just info (which can be called default).

Can we see it with links in the text? (styled black, and visited links stay black)

Can we see a version with checks instead of bullets? And an ordered list version?

Is the background blue set up as a color setting?

**Comment by ardenk** [comment]
@3DX8 list items should have a little margin between them to differentiate the blocks of text.

**Comment by 3DX8** [comment]
> @3DX8 There should not be success, warning, or error states for this. Just info (which can be called default).
[RESPONSE] OK, but are we still planning on giving them the ability to change the color if they want? I can provide those classes if so but not display them in the examples...
> Can we see it with links in the text? (styled black, and visited links stay black)
[RESPONSE] Yes I'll work on that
> Can we see a version with checks instead of bullets? And an ordered list version?
[RESPONSE] OK I'll push up another version with these examples
> Is the background blue set up as a color setting?
[RESPONSE] No it's set up to use the standard "info" and "info-lighter" classes... I went the route of alerts which only gives font and border width settings. I could add it in the settings file as a variable if you think that's a good idea?

**Comment by 3DX8** [comment]
Hi @ardenk, @jaredcunha here are some Summary box updates:
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3774-Summary-Box/components/detail/summary-box.html

- removed standard color names (info, success, warning, error) as variant class names and moved color customizations to the settings files (*see Summary box settings variables below)
- added checkmark and ordered list examples (*see Checkmarks)
- border width is customizable, default is 1px
- added margins between text blocks
- default links are almost black (ink) but are customizable (see $theme-summary-box-link-color)
    - the hover state removes the underline
    - the visited state is ensured to stay black or whatever color $theme-summary-box-link-color is set to
- Anchor names have been addressed so that "usa-anchor-" is been prepended to the href
    - suggested format is href="#usa-anchor-[link-text]" 
    - prevents potential duplicate targets on a page (i.e. if an id was set to [link-text]).

*Summary box settings variables:
$theme-summary-box-background-color: "info-lighter";
$theme-summary-box-border-color: "info";
$theme-summary-box-border-width: 1px;
$theme-summary-box-font-family: "ui";
$theme-summary-box-link-color: "ink";

Change $theme-summary-box-background-color and $theme-summary-box-border-color to any other combination like "warning-lighter" and "warning" for yellow theme or "success-lighter" and "success" for green.

*Checkmarks:
Currently they are the HTML entity version of checkmarks (https://dev.w3.org/html5/html-author/charref) for now. I figure we are holding out until the icons are ironed out.

Standing by for feedback, thanks!
Mitch

**Comment by ardenk** [comment]
@3DX8 for the checklist...

1. Can you use the check [icon](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/accelerator/icons/components/icons/)?

2. Can the indentation work like a bulleted list?
image

**Comment by 3DX8** [comment]
Thanks @ardenk I'm working on this today and will sync up with @jaredcunha on the use of the checkmark icon.

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
