### PR TITLE
[app] unnest h4 from li element in footer

### LINKED ISSUE #1659: Footer - Topic part of list items
**Issue**:
The H4 Topic is part of the list items

**Solution**:
Remove the H4 for the list items

Example:
 ```html
<h4>Topic</h4>
<ul class="usa-unstyled-list usa-width-one-fourth usa-footer-primary-content">
  <li><a href="javascript:void(0);">Secondary link</a></li>
  <li><a href="javascript:void(0);">Secondary link</a></li>
  <li><a href="javascript:void(0);">Secondary link</a></li>
  <li><a href="javascript:void(0);">Secondary link</a></li>
</ul>
```

### PR DESCRIPTION
**Pull request by el-mapache**
## Description

Header elements cant be children of `li`s, this PR promotes the heading in a footer nav to be a sibling of the `ul`.

## Additional information

I had to make some minor CSS additions to get the nav to display consistently

[PREVIEW 😎 ](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/ab-new-1659/components/preview/footer--big.html)

Fixes #1659

### CODE REVIEW

**Comment by el-mapache** [comment]
@maya I opened a new PR since the old one had a million conflicts

**Comment by maya** [comment]
Note to myself: Check color of footer: did we change our vars to use the utilities? Seems so.

**Comment by el-mapache** [comment]
@maya can you check this out again?

**Comment by maya** [comment]
@el-mapache yes, it works now! HTML and functionality are good to go. If it works for you, I can assign myself to this to take care of some last CSS and style work/finessing?

**Comment by el-mapache** [comment]
@maya sure, go nuts!

**Comment by el-mapache** [comment]
@maya also, if the visual styles dont actually match what they should be, we might need to add regression tests for this component?

**Comment by maya** [comment]
@el-mapache yeah it looks like the visual regression tester is only running the medium footer (not big or slim) so it makes sense why it wouldn't have failed for you.

**Comment by maya** [comment]
Style fixes are in, this is g2g 🚀

**Pull request merged**
