### PR TITLE
Fix 1 mixed content NetSparker issue

### PR DESCRIPTION
**Pull request by maya**
https://components.designsystem.digital.gov/components/detail/links.html: Change external link from http to https

Not 100% positive what the issue is on https://components.designsystem.digital.gov/components/detail/footer--default.html is, but we changed the http in the SVGs to https.

/cc @wslack

### CODE REVIEW

**Comment by maya** [comment]
@wslack I'm not sure if the SVG change was correct. According to https://www.w3.org/2000/svg, `http://www.w3.org/2000/svg` is an XML namespace.

**Comment by wslack** [comment]
I might be totally wrong; want me to circle back and ask them?

**Comment by maya** [comment]
Yes, please bc `http://www.w3.org/2000/svg` is the valid XML namespace for SVG.

**Comment by wslack** [comment]
KK. Waiting for GSA IT to tell me what the mixed content issue was.

**Comment by maya** [comment]
Merging this, @wslack feel free to give us a heads up if they find out what the second issue was.

**Pull request merged**
