### PR TITLE
Phase 2 components - build errors

### PR DESCRIPTION
**Pull request by amyleadem**
Update to resolve build errors found while running axe-storybook-testing. 

Performed the following fixes:
- Fresh npm install to resolve dependency error
- Updated Accordion component to use an acceptable "multiselectable" attribute  (MARKUP CHANGE)
- Updated Card component to remove the <header> element inside the component (MARKUP CHANGE)
- Updated File Input twig file to find appropriate JSON item
- Updated modal~large json to include close button data

### CODE REVIEW

**Comment by amyleadem** [comment]
[Error list](https://app.circleci.com/pipelines/github/uswds/uswds/3158/workflows/6301cbd0-d5fd-4d40-9a19-973d2bd2553e/jobs/7559/parallel-runs/0/steps/0-109):

1) [chromium] accessibility
     Components/Accordian
       Multiselectable
       Detected the following accessibility violations!
       1. aria-allowed-attr (Elements must only use allowed ARIA attributes)
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/aria-allowed-attr?application=axeAPI.
          Check these nodes:
          - html: <div class="usa-accordion usa-accordion--multiselectable" aria-multiselectable="true">
            summary: Fix any of the following:
                       ARIA attribute is not allowed: aria-multiselectable="true"

NOTE: 
- [wai-aria standards for multiselectable](https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-multiselectable)
- Allowed on the following roles:
- [grid](https://www.w3.org/TR/wai-aria-1.0/roles#grid)
- [listbox](https://www.w3.org/TR/wai-aria-1.0/roles#listbox)
- [tablist](https://www.w3.org/TR/wai-aria-1.0/roles#tablist)
- [tree](https://www.w3.org/TR/wai-aria-1.0/roles#tree)
- Not compatible with this role

2) [chromium] accessibility
     Components/Card
       Default
       Detected the following accessibility violations!
       1. landmark-no-duplicate-banner (Document should not have more than one banner landmark)
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default card</h2>
                  </header>
            summary: Fix any of the following:
                       Document has more than one banner landmark
       
       2. landmark-unique (Ensures landmarks are unique)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default card</h2>
                  </header>
            summary: Fix any of the following:
                       The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

3) [chromium] accessibility
     Components/Card
       Flag

       Detected the following accessibility violations!
       
       1. landmark-no-duplicate-banner (Document should not have more than one banner landmark)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default flag</h2>
                  </header>
            summary: Fix any of the following:
                       Document has more than one banner landmark
       
       2. landmark-unique (Ensures landmarks are unique)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default flag</h2>
                  </header>
            summary: Fix any of the following:
                       The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

4) [chromium] accessibility
     Components/Card
       Media

       Detected the following accessibility violations!
       
       1. landmark-no-duplicate-banner (Document should not have more than one banner landmark)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default media</h2>
                  </header>
            summary: Fix any of the following:
                       Document has more than one banner landmark
       
       2. landmark-unique (Ensures landmarks are unique)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Default media</h2>
                  </header>
            summary: Fix any of the following:
                       The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

5) [chromium] accessibility
     Components/Card
       Standard

       Detected the following accessibility violations!
       
       1. landmark-no-duplicate-banner (Document should not have more than one banner landmark)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Card</h2>
                  </header>
            summary: Fix any of the following:
                       Document has more than one banner landmark
       
       2. landmark-unique (Ensures landmarks are unique)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=axeAPI.
       
          Check these nodes:
       
          - html: <header class="usa-card__header">
                    <h2 class="usa-card__heading">Card</h2>
                  </header>
            summary: Fix any of the following:
                       The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

6) [chromium] accessibility
     Components/File Input
       Error

       Detected the following accessibility violations!
       
       1. duplicate-id-aria (IDs used in ARIA and labels must be unique)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria?application=axeAPI.
       
          Check these nodes:
       
          - html: <span class="usa-hint" id="NaN">Select any valid file</span>
            summary: Fix any of the following:
                       Document has multiple elements referenced with ARIA with the same id attribute: NaN

7) [chromium] accessibility
     Components/Modal
       Large

       Detected the following accessibility violations!
       
       1. button-name (Buttons must have discernible text)
       
          For more info, visit https://dequeuniversity.com/rules/axe/4.4/button-name?application=axeAPI.
       
          Check these nodes:
       
          - html: <button class="usa-button usa-modal__close" aria-label="" data-close-modal="">
                    <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
              <use xlink:href="./img/sprite.svg#close"></use>
            </svg>
       
                  </button>
            summary: Fix any of the following:
                       Element does not have inner text that is visible to screen readers
                       aria-label attribute does not exist or is empty
                       aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
                       Element has no title attribute
                       Element's default semantics were not overridden with role="none" or role="presentation"

**Comment by amyleadem** [comment]
Resolved Issue 7 - added close_button data for modal~large.json.

**Comment by amyleadem** [comment]
Resolve: Issue 6 File Input
Name was already declared in the file-input variable, so I removed it from all references in the twig

**Comment by amyleadem** [comment]
Resolved: Issues 2-6 - Card component landmark errors
Replaced <header> with <div> inside the card component

**Review by mejiaj — APPROVED** [review]

**Pull request merged**
