### PR TITLE
USWDS - Banner: Align building shape to center of icon

### LINKED ISSUE #5352: USWDS - Bug: "dot gov" icon is off center
### Describe the bug

The icon in [uswds/packages/usa-banner/src/img/icon-dot-gov.svg](https://github.com/uswds/uswds/blob/90a493564c4768baf494fa8946fccef74253f000/packages/usa-banner/src/img/icon-dot-gov.svg) (the "dot gov" icon for the banner component) is not centered within the circle.

### Steps to reproduce the bug

1. Open icon-dot-gov.svg in your image editor of choice.
2. Create rectangles extending from each edge of the central icon to the edge of the circle, like so:
Screenshot 2023-06-23 at 4 22 20 PM

3. Observe that one rectangle has a higher width than the other one (~18.9 vs ~20.5). It's not vertically centered either (it's too far up), though that might be justifiable as the icon isn't symmetrical vertically.

### Expected Behavior

The icon is centered horizontally, and possibly vertically.

### Related code

_No response_

### Screenshots

_No response_

### System setup

* USWDS version: latest "develop" branch. Icon unchanged since at least v3.0.0, the git history gets murky after that.

### Additional context

The other icon in the banner (the https lock icon) is fine.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by patrickcate**
# Summary
Improved horizontal alignment in `icon-dot-gov.svg`.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5352

## Related PR
[Changelog PR](https://github.com/uswds/uswds-site/pull/2267)

### CODE REVIEW

**Comment by amyleadem** [comment]
Thanks for submitting this PR. I have added a few core team members as reviewers. We will let you know if we have any questions.

**Review by mahoneycm — APPROVED** [review]
Provides a nice visual improvement! After building the components and comparing them, it's easy to tell this svg is more centered.

- [x] No build errors
- [x] Banner displays correctly
- [x] Icon is visually enhanced

**Review by amyleadem — APPROVED** [review]
This looks good to me. Confirmed with the design team that the element is centered inside the circle. 

For reference, I layered the two logos, with the old version in red and the new version in blue. It shows that the element has shifted slightly to the right. 

image

**Review by mejiaj — APPROVED** [review]
Thanks for fixing this!

**Review by thisisdano — APPROVED** [review]
Thank you!

**Pull request merged**
