### PR TITLE
Remove duplicate css

### PR DESCRIPTION
**Pull request by hursey013**
This removes the duplicate css identified in https://github.com/uswds/uswds/issues/2361

The `box-sizing` at the top of the compiled  stylesheet was being brought in by Bourbon Neat, so in order to remove it the `$border-box-sizing` has to be set to false. I created a vendor variables partial in order to set that before Bourbon in added. The alternative would be to continue to rely on Bourbon Neat, and remove the duplicate code from `core/_base.scss` but it seems more flexible for us to be able to control those rules vs it being injected by an a third party library.

Bourbon Neat also sets a default `$max-width` that is used with the `outer-container` mixin, which is why we were having to specify a second `max-width` with `$site-max-width` to override it. The `outer-container` actually takes the max-width as an argument though, so I updated all the occurrences of it to pass in `$site-max-width` which makes adding the second max-width unnecessary.

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/bh-duplicate-css)

### CODE REVIEW

**Comment by maya** [comment]
Sounds good, thinking future friendly, if/when we upgrade to Neat 2.0 do the names of the variables have to change?

**Comment by maya** [comment]
This creates a new top-level folder in stylesheets `vendor/` and I wonder if it's confusing since we already have a `lib`. Would we be able to add a `variables-vendor.scss` in `core` instead?

**Comment by hursey013** [comment]
Unfortunately it looks like both `$max-width`, `$border-box-sizing`, and the `outer-container` mixin are removed in later versions so I don't think we can count on any of those. Is the plan to update Neat to 2.0 in the near future? Because if that is the case I think this issue is larger than duplicate code.

I agree a new folder is probably overkill to set one variable, I'll refactor it as you suggested.

**Comment by maya** [comment]
Upgrading to Neat 2.0 is TBD, but I think we definitely want to improve grids in general (some thinking started in #2137), likely as part of the USWDS 2.0 release. It's good to keep on our radar its changes, in any case, thanks!

**Pull request merged**
