### PR TITLE
[Accordion]: Revert overwritten 2.0 changes

### LINKED ISSUE #2648: 2.0 accordion was overwritten by 1.0 accordion
It looks like this commit https://github.com/uswds/uswds/commit/118c0b0e8ffc1be0e5e70ece834cc8e225f77155#diff-892b1d25097ad1baaf33cac3a950176c saved over 2.0 work from the develop branch. I see this bc the [new 2.0 accordion](https://github.com/uswds/uswds/pull/2360) was saved over, replaced by the old accordion.

@el-mapache the JS changed in this too, should see how this affects any new work you did here.

What's an unknown is whether other 2.0 work was overwritten as well.

### PR DESCRIPTION
**Pull request by el-mapache**
## Description

Some changes we wanted to preserve were overwritten, this puts them back!

Fixes #2648

### CODE REVIEW

**Comment by thisisdano** [comment]
@maya you're probably most qualified to evaluate this

**Comment by maya** [comment]
Yep! Swapped myself to review.

**Comment by maya** [comment]
@el-mapache is this working on your end? Doesn't seem to be on the preview branch: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/ab-2648/components/preview/accordion--bordered.html

Also, looks like the style got borked somehow 😬

**Comment by el-mapache** [comment]
@maya can you check this out again please? I've made some changes, but I'm not 100% sure if it looks like you'd expect the 2.0 accordion to look. Thanks!

**Comment by maya** [comment]
@el-mapache sure! Did you push the changes up? Not seeing any new commits.

**Comment by el-mapache** [comment]
sorry about that 😬 @maya. should be good now!

**Comment by maya** [comment]
@el-mapache yay, the accordion is working now! I can take the styling from here, since they're looking huge.

**Comment by el-mapache** [comment]
@maya thanks, I'm not sure why the padding blew up so much

**Comment by maya** [comment]
@el-mapache fixed the styles in ad932e8 so now they're matching what we have.

**Comment by nolawi** [comment]
@maya is this change in the latest release, some how accordions are not triggering the proper styles for me.

**Comment by maya** [comment]
Hi @nolawi, which "latest release" are you referring to? It's in the latest code in the [`release-2.0`](https://github.com/uswds/uswds/tree/release-2.0) branch, but not in 1.x. [Preview of the accordion](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/accordion--default.html).

**Comment by nolawi** [comment]
this is awesome thank you for sharing @maya - the issue was in the upgrade of 1.x- 1.7- I do not think its related to this.

**Pull request merged**
