### PR TITLE
USWDS-3355 USWDS-3357 Date Picker Component

### LINKED ISSUE #3355: Create a date picker component.
## User Story

As a front-end developer, I need a way to help users select a single date in a way that is compact, functional, and accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#date-picker)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/combinations/date-picker.page?)
* [Shopify](https://polaris.shopify.com/components/forms/date-picker#navigation)
* [Atlassian](https://atlaskit.atlassian.com/packages/core/datetime-picker)
* [Carbon](https://www.carbondesignsystem.com/components/date-picker/code/)

## Reference
* [A New Day: Making a Better Calendar - Gerard Cohen - 12/05/2018](https://www.24a11y.com/2018/a-new-day-making-a-better-calendar/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Accessibility validation
- [ ] Conduct usability test with working code
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets

### LINKED ISSUE #3357: Create a date range picker component.
## User Story

As a front-end developer, I need a way to help users select a date range in a way that is compact, functional, and accessible.

## Examples
* [USPTO](https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#date-picker)
* [Mercury](https://www.canadapost.ca/cpc/en/designsystem/mercury/components/combinations/date-picker.page?)

## Reference
* [Designing The Perfect Date And Time Picker - Vitaly Friedman - 07/05/2017](https://www.smashingmagazine.com/2017/07/designing-perfect-date-time-picker/)

## Checklist
- [ ] Create low-fidelity design
- [ ] Review & discuss low-fi design (designer + developers)
- [ ] Get user feedback on low-fi designs (optional - if team feels is needed)
- [ ] Code
- [ ] Conduct usability test with working code (optional - if team feels is needed)
- [ ] Create hi-fi design assets (Adobe XD, Sketch, Figma)
- [ ] Review & approve hi-fi design assets
- [ ] Publish design assets (update downloadable files for Adobe XD, Sketch, Figma)

### PR DESCRIPTION
**Pull request by wbyoko**
Single date picker component, tests, styles, fractal example
Date range picker component, tests, styles, fractal example

Closes #3355
Closes #3357

[Current Implementation](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/10x-forms/3355-date-picker/components/preview/date-picker.html)

## Additional information
Screenshot 2020-05-08 19 22 26
Screenshot 2020-05-08 19 22 58
Screenshot 2020-05-08 19 23 42
Screenshot 2020-05-08 19 24 13
Screenshot 2020-05-08 19 47 18
Screenshot 2020-05-27 18 25 09

## Test Cases
* should enhance the date input with a date picker button
* should display a calendar for the current date when the date picker button is clicked
* should hide the calendar when the date picker button is clicked and the calendar is already open
* should close the calendar you click outside of an active calendar
* should display a calendar for the inputted date when the date picker button is clicked with a date entered
* should allow for the selection of a date within the calendar
* should allow for navigation to the preceding month by clicking the left single arrow button within the calendar
* should allow for navigation to the succeeding month by clicking the right single arrow button within the calendar
* should allow for navigation to the preceding year by clicking the left double arrow button within the calendar
* should allow for navigation to the succeeding year by clicking the right double arrow button within the calendar
* should display a month selection screen by clicking the month display within the calendar
* should allow for the selection of a month within month selection screen
* should display a year selection screen by clicking the year display within the calendar
* should allow for navigation to the preceding dozen years by clicking the left single arrow button within the year selection screen
* should allow for navigation to the succeeding dozen year by clicking the right single arrow button within the year selection screen
* should allow for the selection of a year within year selection screen
* should close the calendar when escape is pressed within the calendar
* should move focus the to the same day of week of the previous week when up is pressed from the currently focused day
* should move focus the to the same day of week of the next week when down is pressed from the currently focused day
* should move focus the to the previous day when left is pressed from the currently focused day
* should move focus the to the next day when right is pressed from the currently focused day
* should move focus the to the first day (e.g. Sunday) of the current week when home is pressed from the currently focused day
* should move focus the to the last day (e.g. Saturday) of the current week when end is pressed from the currently focused day
* should move focus the to the same day of the previous month when page up is pressed from the currently focused day
* should move focus the to the last day of the previous month when page up is pressed from the the last day of a longer month
* should move focus the to the same day of the next month when page down is pressed from the currently focused day
* should move focus the to the last day of the next month when page down is pressed from the the last day of a longer month
* should move focus the to the same day of the month January when page down is pressed from the currently focused day in December
* should move focus the to the same day/month of the previous year when shift + page up is pressed from the currently focused day
* should move focus the to February 28th of the previous year when shift + page up is pressed from a focused February 29th date of a leap year
* should move focus the to the same day/month of the next year when shift + page down is pressed from the currently focused day
* should move focus the to February 28th of the next year when shift + page down is pressed from a focused February 29th date of a leap year
* should accept a parse-able date with a two digit year and display the calendar of that year in the current century
* should show an improper date as invalid as the user leaves the input
* should validate the input when a date is selected

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by Ben-Judy-Flexion** [comment]
Looks good to me!

**Comment by thisisdano** [comment]
There isn't enough contrast between the range start background and the text color: can the text in the range start be white (white's probably the color least likely to trigger contrast issues with use values of `primary-vivid`)

NB: I will have a fix soon (included in https://github.com/uswds/uswds/pull/3492) that will automatically calculate the proper value text based on a specific background, and we could apply that change here when it is done.

**Comment by thisisdano** [comment]
I think I've managed to misunderstand what the non-focus outline indicator is supposed to indicate. Is it the last-focussed element/day? When I page between months, I see the indicator persistent from month to month, which I guess is not what I expect. Did I just confuse myself or is something wrong here?

outline-persistence

**Comment by wbyoko** [comment]
@dano The dark blue outline is what indicates that is the currently focused date would be within the calendar when tabbing in. So if you were using tab to circulate between the buttons that would be the date to would land on.

**Pull request merged**
