### PR TITLE
[WIP] Fix typography spacing

### PR DESCRIPTION
**Pull request by maya**
Seeks to ensure typography consistently displays proper margins in different use cases (from simple layouts to complex grids). There were some issues with typography spacing in different contexts (grid, columns, section classes).

Changes include:
* Going one-directional in paragraph text `p` margins (by using top margins only) to help with typography stacked inside multiple elements
* Remove top margins of elements in the first grid item column items and leaves the following grid items with their natural spacing
* When using the section classes (`usa-section`) which provide top and bottom spacing, remove the top and bottom margins of first and last elements inside it respectively, so that the section's spacing provides the intended spacing. 

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/fix-typography-spacing/components/detail/type-spacing.html)

This is very much a work-in-progress and tries to show examples of possible solutions.

Screenshot of the preview linked: black outline is the `usa-grid` class and red outline is the `usa-width-*` classes:
127 0 0 1_3000_components_preview_type-spacing

Fixes: #2215.

### CODE REVIEW

**Comment by alex-page** [comment]
We recently solved this problem using lobotomised owls in our [design system](https://gold.service.gov.au/), you can take a look at an example here:
https://github.com/govau/uikit/blob/master/packages/accordion/src/sass/_module.scss#L27

Our inspiration came from this detailed article:
https://alistapart.com/article/axiomatic-css-and-lobotomized-owls

If you want to collaborate on solving this issue let me know! Happy to help.

**Comment by maya** [comment]
@alex-page Thanks! The technique that we use is similar to a scoped version of that but it still causes some issues which is the reason for this PR. I've also heard from Heydon Pickering previously that even he doesn't recommend that technique on existing projects, it's much easier to add from the beginning. 

P.S. Great job on GOLD. Looks SOLID! 🥇

**Comment by melwoodard** [comment]
:wave: a bunch of us on the Vets.gov team at DSVA are super excited to see this PR happening! 

We've been wanting to approach spacing for some time and add some more sophisticated rules to allow content to line up right in different scenarios, and were really happy to see this happening within USWDS instead of rolling our own overrides. 

Any sense of timing for when this might be available in the design system?

**Comment by maya** [comment]
@melwoodard thanks for your interest in this work! We're excited that this is something you're looking for. This work would likely make its way into our next major release (2.0) which is around a couple of months away. If you are able to use this work in your project and let us know how it's working for you, that would be great feedback for us and go a long way to making this update stronger and validated.

**Comment by el-mapache** [comment]
@maya How is this coming along? Its been open for a bit so I just wanted to give it a lil bump

**Comment by maya** [comment]
No updates yet, will probably work on this after #2241. If you'd like to get a better understanding of the issue, check out #2215 and GOV.UK's solution: https://github.com/uswds/uswds/issues/2215#issuecomment-405679277.

**Comment by maya** [comment]
Closing this PR in favor of #2696.

/cc @alex-page @melwoodard let us know what you think!

**Pull request closed without merging**
