### PR TITLE
Make return to top link set focus on main content

### PR DESCRIPTION
**Pull request by hursey013**
This enables the `Return to top` link to set the focus on the main content area so that tabbing does not skip back to the footer links.

It is backwards compatible so if the return to top link is set to `#` (which it is in all of our documentation), it will override that and instead set it to `#main-content` (if it exists). If folks have manually set the link to target a different element, it should still also work as it did before, but will also reset the focus to the specified target.

This addresses https://github.com/uswds/uswds/issues/2321

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/bh-return-top)

### CODE REVIEW

**Comment by hursey013** [comment]
I think we may also want to update our documentation and default HTML in the footer component to change the link from `#` to `#main-content` so that it is more transparent on what the intended functionality is - what do you think @maya?

**Comment by maya** [comment]
Agree with these changes... a few things:

1. I'm testing the changes on the [docs page](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/bh-return-top/components/preview/layout--docs.html#main-content). Everything is good the first time. After I click it the first time, then scroll back to the bottom and click it again, nothing happens.

2. Can we remove the visible focus from the `#main-content`? It's not necessary for content and find it doesn't look clean.
screen shot 2018-03-20 at 9 16 35 am

**Comment by hursey013** [comment]
@maya I took another pass, let me know if it's 👍

**Comment by maya** [comment]
@hursey013 did you push it up yet? Not seeing any new commits.

**Comment by hursey013** [comment]
@maya Oops, there now 😬

**Comment by maya** [comment]
I tested this with VoiceOver. 

What I expected was how it works with the skipnav link which announces that I'm on the main:

screen shot 2018-03-20 at 12 39 06 pm

The way I experienced the back to top link was this (rattles off the sidenav items):

screen shot 2018-03-20 at 12 44 19 pm

Can we bring the two in line with each other to get the back to top link behavior consistent with the skipnav behavior?

**Pull request merged**
