### PR TITLE
USWDS | 4194 component specific dependencies

### PR DESCRIPTION
**Pull request by scottqueen-bixal**
Closes https://github.com/uswds/uswds/pull/4196

## Description

This builds on the great work proposed by kmonahan.

if we consider the change
```
    ".": {
      "import": "./dist/js/uswds.min.js",
      "default": "./dist/js/uswds.min.js"
    },
    "./src/js/components": "./src/js/components/index.js",
    "./src/js/components/*": "./src/js/components/*.js"
```
and reference the [documentation](https://webpack.js.org/guides/package-exports/) recommended by sawyerh for webpack 5

we should be interpreting this change to allow folks who call

`import "uswds"` === `./dist/js/uswds.min.js` 

while still allowing others who might call the import for

` import USWDS from "uswds/src/js/components/"` and we should still be able to destructure, `const { tooltip } = USWDS`

OR, if they choose to import components individually 

` import tooltip from  "uswds/src/js/components/tooltip"`

and still, instantiate the js in the  lifecycle

ie. `tooltip.on()`

These changes seem to work well at first pass - we still need to do the following

### TODO
- [x] test fix on https://github.com/sawyerh/uswds-webpack-example as a working webpack example
- [x] test fix on https://github.com/scottqueen-bixal/uswds-combo-box-example as a working example directed by USWDS documentation
- [x] update documentation https://designsystem.digital.gov/documentation/developers/#js-customization

as needed...
- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by scottqueen-bixal** [comment]
confirming that applying the fix to https://github.com/sawyerh/uswds-webpack-example resolves the error reported  here https://github.com/uswds/uswds/issues/4194

### Steps to confirm 
Clone this [repo](https://github.com/sawyerh/uswds-webpack-example)
Follow the readme instructions 

```sh
ERROR in ./src/index.js 6:0-54
Module not found: Error: Package path ./src/js/components/tooltip is not exported from package /Users/squeen/Projects/uswds-webpack-example/node_modules/uswds (see exports field in /Users/squeen/Projects/uswds-webpack-example/node_modules/uswds/package.json)
```

Navigate to `node_modules/uswds/package.json`
Update @line 164

```json
  "exports": {
    ".": {
      "import": "./dist/js/uswds.min.js",
      "default": "./dist/js/uswds.min.js"
    },
    "./src/js/components": "./src/js/components/index.js",
    "./src/js/components/*": "./src/js/components/*.js"
  },
```
Save, `npm run build`

confirm success 

```sh
asset main.js 6.31 KiB [compared for emit] [minimized] (name: main) 1 related asset
runtime modules 663 bytes 3 modules
modules by path ./node_modules/ 19.3 KiB
  modules by path ./node_modules/uswds/src/js/ 13.5 KiB
    modules by path ./node_modules/uswds/src/js/utils/*.js 2.12 KiB 3 modules
    ./node_modules/uswds/src/js/components/tooltip.js 11.4 KiB [built] [code generated]
    ./node_modules/uswds/src/js/config.js 39 bytes [built] [code generated]
  modules by path ./node_modules/receptor/ 2.77 KiB
    ./node_modules/receptor/behavior/index.js 1.75 KiB [built] [code generated]
    ./node_modules/receptor/delegate/index.js 273 bytes [built] [code generated]
    ./node_modules/receptor/delegateAll/index.js 594 bytes [built] [code generated]
    ./node_modules/receptor/compose/index.js 174 bytes [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
  ./node_modules/element-closest/element-closest.js 895 bytes [built] [code generated]
./src/index.js 236 bytes [built] [code generated]
webpack 5.37.0 compiled successfully in 627 ms
```

**Comment by scottqueen-bixal** [comment]
It is more difficult to test https://github.com/scottqueen-bixal/uswds-combo-box-example because it relies on https://www.npmjs.com/package/react-scripts ([github](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L86))which is still on version `"webpack": "4.44.2",`

Even if we `eject` the app and try to update webpack that way, the scripts will break.

What we can confirm is that the change won't impact someone still relying on a webpack 4 dependency.

### Steps to confirm
Clone this [repo](https://github.com/scottqueen-bixal/uswds-combo-box-example)
Navigate to `node_modules/uswds/package.json`
Update 
```json
  "exports": {
    ".": {
      "import": "./dist/js/uswds.min.js",
      "default": "./dist/js/uswds.min.js"
    },
    "./src/js/components": "./src/js/components/index.js",
    "./src/js/components/*": "./src/js/components/*.js"
  },
```
Save, `npm run build`

confirm no-error-success app should still build as expected

**Comment by scottqueen-bixal** [comment]
Since webpack 4 still works with our recommended process, React/Angular are still working with webpack4, maybe we should keep the documentation for those recommendations there. 

It is probably also a good idea to make note of webpack 5 taking advantage of the export field so those using it, will have some direction.

Documentation has been updated with this consideration.

**Review by mejiaj — APPROVED** [review]

**Comment by sawyerh** [comment]
Thanks @scottqueen-bixal!

**Pull request merged**
