### PR TITLE
USWDS - Flex: Test and ensure flex shorthands work across browsers.

### LINKED ISSUE #3386: [sass] Flex fill on IE11.
## Description

`@include u-flex("fill");` documented here:
https://designsystem.digital.gov/design-tokens/flex/

Using it to grow vertically results in something like this:

### IE11
image

---

Changing it from:
```scss
flex: 1 0 0 → flex: 1 0 auto
```
Fixes it in IE11.

## Steps to reproduce the issue

1. Checkout `feature/USWDS-3301`
2. Go to commit `8fbfc1c`
3. Compile SCSS 
4. `npm run start`
5. Open `http://localhost:3000/components/preview/card--equal-height` in IE11

---
Updated

## Expected behavior
Flex fill **should** behave consistently across all browsers

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

Fixes #3386. This should ensure flex properties work across all browsers. Currently `flex-fill` has been known to cause issues in IE11.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by mejiaj** [comment]
Added `0%` values to flex shorthands to get them working in IE11. Based on this [guidance](https://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs#avoiding-unitless-flex-basis) by Philip Walton. 

I've also created this flex test page [here](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-test-flex/components/preview/flex.html).

### Problem
Unitless flex shorthand is causing incorrect widths in IE11.

#### Firefox
image


#### IE11
image

---

The only problem left is minification from CSSO keeps stripping the `%` from `0%`. This was fixed in the latest release https://github.com/css/csso/releases/tag/v4.0.3

But that change hasn't made it to the plugin we're using
https://www.npmjs.com/package/postcss-csso

**Comment by thisisdano** [comment]
I was able to update `postcss-csso` to use the most recent `csso` so I think this PR is good to go!

**Comment by thisisdano** [comment]
Modified to use `1` as a shrink value. This prevents elements from extending beyond the boundaries of the flex parent:

**Before**

Screen Shot 2020-06-15 at 8 46 09 PM


**After**

Screen Shot 2020-06-15 at 8 42 31 PM
Screen Shot 2020-06-15 at 8 42 46 PM
Screen Shot 2020-06-15 at 8 42 55 PM

**Comment by mejiaj** [comment]
Everything looks good. Thanks for the change!

**Pull request merged**
