### PR TITLE
Update vars to v2

### PR DESCRIPTION
**Pull request by thisisdano**
🔍 [Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/dw-vars-v2/)

- - - 

- Removed lots of v1 vars and made sure they had v2 equivalents
- Moved all component-related settings into a `settings-components` file
- Renamed some vars around component-based organization 
- Removed redundant or unused internal vars
- Removed variables that should be a function instead (like `$color-primary-lighter`)

### CODE REVIEW

**Comment by maya** [comment]
Happy to close #2752 in favor of this, but just want to note that there's a good number of variables we can remove: 
https://github.com/uswds/uswds/pull/2752/files#diff-b5fa828d79411a4653dced7e478b914bR125

**Comment by thisisdano** [comment]
Ah geez, once again I wasn't paying attention and didn't notice your WIP PR

**Comment by thisisdano** [comment]
And yeah — many many vars will go away.

**Comment by thisisdano** [comment]
And yes, let's close #2752 in favor of this

**Pull request merged**
