### PR TITLE
USWDS 3356 - Create tooltip component

### PR DESCRIPTION
**Pull request by jaredcunha**
## Description
Creates an accessible tooltip component, add checks to prevent from appearing outside the viewport and provide support for utility classes.

## Additional information

Screen Shot 2020-05-26 at 3 30 41 PM

Most info appears in this issue:
https://github.com/uswds/uswds/issues/3356

Additionally, the tooltip component:
- works in all relevant browsers
- can be hidden using the keyboard
- can appear on top (default), left, right, or bottom of the element, determined by data attribute.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by jaredcunha** [comment]
Still left to do:
- Clean up examples
- Write website documentation

**Comment by jaredcunha** [comment]
Guidance PR: https://github.com/uswds/uswds-site/pull/963

**Comment by jaredcunha** [comment]
I think one question I have is how USWDS is handling z-indexes? Should we apply one for the tooltip? If so, what should it be?

**Comment by thisisdano** [comment]
So, say I'm using the `data-classes` attribute to add classes that give a tooltip button the same full-width-at-mobile styling that standard buttons have. This feels like a common use case.

Screen Shot 2020-06-29 at 11 37 04 PM

> ABOVE: Tooltip buttons don't cover the full width at mobile because of their enclosing `span`. Note these four buttons are in `tablet:grid-col-3` grid columns

Screen Shot 2020-06-29 at 11 39 30 PM

> ABOVE: Tooltip buttons with `data-classes="width-full tablet:width-auto"`

This works as I expect it for button styling, but the tooltips don't have accurate placement once we get to post-`tablet` widths:

Screen Shot 2020-06-29 at 11 44 36 PM

Is there any way to fix this, or am I using this feature in a non-standard way?

**Comment by jaredcunha** [comment]
@thisisdano Can you let me know what browser and HTML you're using.  Also I think the buttons change at `mobile-lg` (can't remember if that's the name or not) instead of tablet. 

Anyway, this is what I'm trying:
```<div class="grid-row">
  <div class="tablet:grid-col-3 margin-y-2">
    <button data-classes="width-full tablet:width-auto" type="button" class="usa-button usa-tooltip"  data-position="top" title="Tooltip on top">Show on top</button>
  </div>
  <div class="tablet:grid-col-3 margin-y-2">
    <button data-classes="width-full tablet:width-auto" type="button" class="usa-button usa-tooltip"  data-position="bottom" title="Tooltip on bottom">Show on bottom</button>

  </div>
  <div class="tablet:grid-col-3 margin-y-2">
    <button data-classes="width-full tablet:width-auto" type="button" class="usa-button usa-tooltip"  data-position="right" title="Tooltip on right">Show on right</button>

  </div>
  <div class="tablet:grid-col-3 margin-y-2">
    <button data-classes="width-full tablet:width-auto" type="button" class="usa-button usa-tooltip"  data-position="left" title="Tooltip on left">Show on left</button>
  </div>
</div>

<div class="margin-y-2">
  <button class="usa-button">Control button</button>
</div>
```

I'm not getting the same result as you. But I am getting something buggy with the left tooltip:
Screen Shot 2020-06-30 at 8 11 09 AM

When I looked at the inspector, this what I'm seeing. It seems the width utility is not responsive (https://designsystem.digital.gov/utilities/height-and-width/#width)

I can confirm this. Here it with just the utility. Take a look at both the HTML inspector and the CSS inspector (notice the width is still `100%` with `tablet:width-auto` applied:
Screen Shot 2020-06-30 at 8 14 57 AM

Here's the same thing with `width: auto` placed inline on the element.
Screen Shot 2020-06-30 at 8 15 15 AM

**Comment by thisisdano** [comment]
I'm in Chrome and here's the markup. Lemme check on the `width` responsive issue...

```
<div class="grid-row padding-8">
  <div class="tablet:grid-col-3 margin-top-2 text-center">
    <button type="button" class="usa-button usa-tooltip" data-position="top" data-classes="width-full tablet:width-auto" title="Tooltip on top">Show on top</button>
  </div>
  <div class="tablet:grid-col-3 margin-top-2 text-center">
    <button type="button" class="usa-button usa-tooltip" data-position="bottom" data-classes="width-full tablet:width-auto" title="Tooltip on bottom">Show on bottom</button>
  </div>
  <div class="tablet:grid-col-3 margin-top-2 text-center">
    <button type="button" class="usa-button usa-tooltip" data-position="right" data-classes="width-full tablet:width-auto" title="Tooltip on right">Show on right</button>
  </div>
  <div class="tablet:grid-col-3 margin-top-2 text-center">
    <button type="button" class="usa-button usa-tooltip" data-position="left" data-classes="width-full tablet:width-auto" title="Tooltip on left">Show on left</button>
  </div>
</div>
```

**Comment by jaredcunha** [comment]
@thisisdano I had the same result on Firefox copying your code. If `tablet:width-auto` was available, the issue is fixed. I manually wrote the selector into the inspector for the screen recording below.

Screen Recording 2020-06-30 at 12 18 PM

**Comment by thisisdano** [comment]
Excellent — I'll check and see what adding responsive `width` by default does to our footprint

**Comment by thisisdano** [comment]
Once we get this to work, does this seem like a good example for the utility functionality? I was trying to think of something that felt practical and gave a good example of its use case.

**Comment by thisisdano** [comment]
Just tidying up some CI issues, then I should be able to merge.

**Pull request merged**
