### PR TITLE
Merge master into develop (Release 1.6.12)

### PR DESCRIPTION
**Pull request by maya**

### CODE REVIEW

**Comment by maya** [comment]
Should deploy be running on this PR? We don't want to deploy `develop` right?

**Comment by thisisdano** [comment]
I'm unclear what `deploy` is doing. But at first blush, I wouldn't expect anything like a deployment on `develop`.

**Comment by thisisdano** [comment]
Should we move forward on this one?

**Comment by maya** [comment]
Yeah

**Pull request merged**
