### PR TITLE
USWDS: Use new Github issue templates

### PR DESCRIPTION
**Pull request by amyleadem**
## Description
Closes: https://github.com/uswds/uswds/issues/4691

Demo link (Currently in a test repo): [Choose issue type](https://github.com/amyleadem/issue-template/issues/new/choose)

### Purpose
Improve contributor experience by using new Github issue yaml templates. These templates allow us to:
1. Create defined form fields for each entry
2. Add `required` setting for mandatory information
3. Add default labels and assignees (if desired)

### Testing
We will not be able to preview this template in USWDS until it is merged, but you can view the templates in action in this test repo: https://github.com/amyleadem/issue-template
- Test repo: [Issue template demo](https://github.com/amyleadem/issue-template/issues/new/choose)
- Test repo: [Issue template files](https://github.com/amyleadem/issue-template/tree/main/.github/ISSUE_TEMPLATE)

## Additional information

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by amyleadem** [comment]
A couple of questions: 
1. In the bug report, could we create a field for including a code snippet/working demo?
1. Do we want to add these templates to all of our active repos?

**Comment by amyleadem** [comment]
@elisaachen 
I have added the detail from your [issue comment](https://github.com/uswds/uswds/issues/4691#issuecomment-1154234948) to the bug report description. Please review and let me know if you need any changes. 
Preview link: [Bug report demo](https://github.com/amyleadem/issue-template/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage%2CNeeds%3A+Confirmation&template=bug_report.yaml&title=USWDS+-+Bug%3A+%5BYOUR+TITLE%5D)

I also had a couple of outstanding questions in the [comment above](https://github.com/uswds/uswds/pull/4789#issuecomment-1150173552). Wanted to flag it in case you had input. Please let me know if you have any questions!

**Comment by elisaachen** [comment]
> @elisaachen I have added the detail from your [issue comment](https://github.com/uswds/uswds/issues/4691#issuecomment-1154234948) to the bug report description. Please review the [bug report demo](https://github.com/amyleadem/issue-template/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage%2CNeeds%3A+Confirmation&template=bug_report.yaml&title=USWDS+-+Bug%3A+%5BYOUR+TITLE%5D) and let me know if you need any changes.
> 
> I also had a couple of outstanding questions in the [comment above](https://github.com/uswds/uswds/pull/4789#issuecomment-1150173552). Wanted to flag it in case you had input. Please let me know if you have any questions! 



> Thanks for incorporating the details. I think description is just missing `a` before the word `workaround`.

**Comment by elisaachen** [comment]
> A couple of questions:
> 
> 1. In the bug report, could we create a field for including a code snippet/working demo?
> 2. Do we want to add these templates to all of our active repos?

1. Sounds like a good idea. To clarify, this would be a working demo of the problem (not solution)? Just want to make sure folks know what to put in there. And this would be optional? 
2. I think so. I don't know of any cons to this right now. As of now, they are all the same templates right?

**Comment by amyleadem** [comment]
> 1. Sounds like a good idea. To clarify, this would be a working demo of the problem (not solution)? Just want to make sure folks know what to put in there. And this would be optional?

I have added the code section to the [bug report](https://github.com/amyleadem/issue-template/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage%2CNeeds%3A+Confirmation&template=bug_report.yaml&title=USWDS+-+Bug%3A+%5BYOUR+TITLE%5D). I set it to optional. Please let me know if you'd like changes. 

> 2\. Do we want to add these templates to all of our active repos?

We do not have currently have consistent issue templates across our repos, but I feel like it would be beneficial if we did. We could start by adding them to our more public-facing repos for now: uswds, uswds-site, uswds-compile, and public-sans.

We can continue to enhance/adjust over time.

**Review by elisaachen — APPROVED** [review]

**Comment by thisisdano** [comment]
I think they should be largely consistent, but a repo like `uswds-site` _could_ have more of a focus on typos/grammar and less on code

**Review by thisisdano — APPROVED** [review]
This is a great improvement

**Pull request merged**
