### PR TITLE
USWDS 3426 - Flex Utilities: Add align-self

### PR DESCRIPTION
**Pull request by taylorsolomon**
## Description

Adds functionality described in #3426

Screen Shot 2020-08-17 at 10 40 55 PM

## Additional information

- The tokens accepted are the same that are used for align-items (duplicated, not referencing the same key-value map)

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by taylorsolomon** [comment]
I'm unsure how to get that federalist/build status to change. I'm guessing that's something that can only be done via a repo owner?

**Comment by thisisdano** [comment]
Thanks @taylorsolomon — checking this out now!

**Comment by thisisdano** [comment]
And yeah, the Federalist build will only trigger for internal branches, so I may move this into an internal branch for more testing.

**Comment by thisisdano** [comment]
Merging into an internal branch for testing. Thanks!

**Pull request merged**
